- misc/scripts/upgrade.sh
What happened is pacstall upgrades in a way that doesn't work anymore and it wanted to upgrade packages like this: `sudo pacstall -I pkg1,pkg2,pkg3` which doesn't work
> Fix upgrade issue

- misc/scripts/install-local.sh
This PR makes pacstall use `editor` (the command to open the default system editor) instead of `nano` to edit pacscripts while installing them.
This may fix  #20
> Resort to using `editor` as last resort

- pacstall
This PR fixes the issue of pacstall showing this warning when removing a package
```
You may want to remove:
```
Its showing `<blank>` as there are no dependencies to show, this PR fixes this
> Fix showing blank dependencies when removing packages

- install.sh
It is a redundant dependency, as it is no longer used. This PR removes that dependency from `install.sh`
> [bug] Remove `fzf` dependency

- misc/scripts/install-local.sh
- pacstall
This is when the installer fails to install stow, so pacstall will install it if not found
> [Feature] Add stow install if not found

- misc/scripts/install-local.sh
The optional dependencies dialog used the wrong form of its/it's. This is unprofessional, so I fixed it. It's nothing to do with any code.
> Fix a typo

- install.sh
Clean install this file doesn't exist and rm complains about it.
```
[+] INFO: making directories
rm: cannot remove '/usr/share/pacstall/repo/pacstallrepo.txt': No such file or directory
[+] INFO: Pulling scripts from GitHub 
```
> Silence rm when the file doesn't exist

- install.sh
Says what it does, no need to `rm` the file, as `touch` already does that.
> [bug] Remove obsolete `rm`

- misc/scripts/install-local.sh
- pacstall
This will export a variable that is only called when something is installing with pacdeps. The metadata logger will see that and log it as `installed as dependency`. If `-Qi` can't find the `$pacstall_depends`, it will print that is was explicitly installed. I'm testing now with `sudo pacstall -I soundux`
> Add basic explicitly installed thingy

- pacstall
When removing a package that doesn't exist, this shows:
```bash
➜  ~ sudo pacstall -R soundux
/bin/pacstall: line 243: /var/log/pacstall_installed/soundux: No such file or directory
[!] ERROR: soundux does not exist or not properly symlinked
```
This pr fixes the no such file or directory
> Fix `-R` showing file error

- misc/scripts/upgrade.sh
When running `sudo pacstall -Up`, pacstall will output something like
this:
```bash
➜  ~ sudo pacstall -Up
[+] INFO: Checking for updates
*exa
.neofetch
@
[+] INFO: Packages can be upgraded
Upgradable: 2
exa neofetch
Do you want to continue? [Y/n] n
```
This commit removes the text below `Checking for updates`
> Fix: Upgrading echo's packages at wrong time

- pacstall
When commit 84e9c7e417de5ca467be6531085f5d19bb6ccbc3 was introduced, it
created a problem with tab completing scripts and issues with how
pacstall works when installing. How it works is if you have package
`foo`, the file will be `foo.pacscript` and you run `pacstall -Il foo`
to install it, but this commit changed it so that you would have to
include the `.pacscript`, so I fixed it
> Fix: suffix issue

- pacstall
So a normal user has a `/home` directory, but what about root? Root's home directory is `/root`. This fixes that
> Fix: /root is not /home/root

- pacstall
```
$ pacstall -Il bat
cat: '~/.local/share/pacstall/repo/pacstallrepo.txt': No such file or directory
/bin/pacstall: line 238: ~/.local/share/pacstall/scripts/install-local.sh: No such file or directory
```
> bash doesn't do tilde expansion in quotes

- misc/scripts/remove.sh
The if is very strange and it will always run and the checking for removescript is done before the sourcing of the file.
Stow is missing --target so it doesn't remove any of the symlink.
> The remove doesn't work

- install.sh
- misc/completion/bash
- misc/completion/fish
- misc/scripts/update.sh
- pacstall
I intend to commit hotfixes for these problems.
> Hotfixes for v1.5.1

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Currently this project has no pull request templates, so the pull request descriptions are kind of all over the place.
This PR solves this problem by adding a `pull_request_template.md` file under `.github/PULL_REQUEST_TEMPLATE`. People will be auto suggested by GitHub in the future to use the template defined in that file when creating pull requests. Hopefully bringing order to the pull request descriptions, once and for all.
> Doc: Add pull request template

- misc/scripts/install-local.sh
`logname` is broken on some systems (like mine) but `$LOGNAME` is not.
change `$(logname)` to `$LOGNAME`.
> Fix: chown uses $(logname) instead of $LOGNAME

- misc/scripts/install-local.sh
`cut` may remove i386 from wine:i386
Use `awk`
> Fix(install): Use `awk` instead of `cut`

- misc/scripts/install-local.sh
Sometimes optional dependencies in are used during building [(like ones in wine)](https://wiki.winehq.org/Building_Wine).
Moves the code which interprets `optdepends` from after building to before.
Fixes #150
> Feat: moves optdepends to before building

- install.sh
- misc/scripts/install-local.sh
This pr will make packages prepare and build inside of fakeroot, allowing for better security
Pacstall will export all possible variables and functions a pacscript can have (obviously some will error, but as long as every variable/function that is in the script is exported, it's fine). Then it can pass into fakeroot
> Feat: Add fakeroot

- misc/scripts/download.sh
- misc/scripts/install-local.sh
- pacstall
Currently the caching in `download.sh` caches pacscripts to  `~/.cache/pacstall`, and it doesn't get cleaned after `install-local.sh` ends 
This changes the caching directory to `/tmp/pacstall/pacscripts/`, and cleans it after `install-local` ends
Fixes #160
> Fix: Caching

- pacstall
It's not recommended to run community scripts as root. So error out like AUR.
Error out when EUID is 0, i.e. user is root
Use EUID, which is equal to 0 when root
> Feat: Error out when running pacstall as root

- misc/scripts/download.sh
- misc/scripts/install-local.sh
In pr #161 (caching), the pacscript is downloaded to
/tmp/pacstall/pacscripts, but during the install, there is a cd to `./*/`, which means that any package past the letter `p` will be unable to cd into
> Fix: (scripts): Fix package install past letter p

- pacstall
Due to the pacscripts being downloaded as root, we couldn't edit it during install.
Removing the `sudo` from download function solves the issue
> Fix: remove unneeded sudo from download

- misc/scripts/install-local.sh
Pacstall tries to copy from `$SRCDIR/$name.pacscript` instead of the location of the local pacscript
Fix the copy command at the end of `install-local.sh`
#170
> Fix (scripts): Copy from the correct location

- misc/scripts/install-local.sh
Deb-control (dummy package) requires version to start with digit
Add "0-" before version starting with letter
> Fix: deb-control requires version to start with digit

- misc/scripts/install-local.sh
The extra `:any` extention on optdepends dummy deb line breaks `:i386` dependencies, for example. Removing it fixes the problem without causing new issues.
This was added while testing fixes and shouldn't be here anymore.
> Rem: remove architecture `:any` extention

- misc/scripts/install-local.sh
When installing multiple programs at once, variables left over may affect later installs
It unsets the affected variables in cleanup
> Feat: Unset variables in `install-local.sh` cleanup

- misc/scripts/install-local.sh
- .deb versions need to have a numerical revision number after the `-`
- the `replace` field starts with a lot of spaces and ends with `\n`, messing up dpkg
- replace the `0-` before files with `0` and add `-1` after
- remove the leading spaces and the ending `\n`
> Various deb-control fixes

- misc/scripts/install-local.sh
A lot of systems have a broken logname program
I replaced $(logname) with $LOGNAME but the code replaces $LOGNAME with $(logname) unless $(logname) fails
That was a terrible way to phrase it
> Replace $(logname) with $LOGNAME

- misc/scripts/remove.sh
Pacstall is not removing the metadata of deb packages when uninstalling
> FIx(scripts): add metadata removal for `-deb`

- pacstall
`pacstall -L` does not list deb packages installed with pacstall
> Fix(scripts): `-L` not listing deb packages

- misc/scripts/install-local.sh
&> was not able to ignore the "errors" so I suggest using 2> instead
> dpkg ignore dependency "errors"

- misc/scripts/download.sh
- pacstall
Some portions of the code base concerned with downloading stuff from the internet can be optimized for greater speed.
Replace current code with speed efficient code.
> feat: Download optimizations

- README.md
The current README file states commands with `sudo`s, which is wrong since v1.5
Update the README
> rem(readme): Unnecessary `sudo`s

- api/config.py
Writing the config directories, and possibly other stuff in the future in the main pacstall file would entail that every other file trying to access those values would have to import a *possibly* giant file. Which is not good for performance, and logistics.
Write the configuration stuff in `api/config.py` module, so in future we can import this shorter file.
> feat(api): Add config module

- misc/scripts/update.sh
- misc/scripts/upgrade.sh
There are two redundant confirmation requests in `update`, `upgrade`.`sh`es.
This PR removes them
> rem(scripts): Remove redundant confirmations

- misc/scripts/upgrade.sh
We found a bug in `ver_compare` function.
Link: https://discord.com/channels/839818021207801878/883613281514840105/883618948225060905
Changes `second`'s operating parameter to `${2}`
Bug introduced in: https://github.com/pacstall/pacstall/commit/b98013c769c4b06f0cda244b7f7b046e45feb2a7
> fix(upgrade): `ver_compare` issue

- misc/scripts/install-local.sh
Fixes #241
Append `2> /dev/null`
> fix(scripts): Redirect `cd` errors to `/dev/null`

- misc/scripts/upgrade.sh
```bash
henry@twilight ~ % ››› pacstall -Up
[+] INFO: Checking for updates
dpkg: error: --compare-versions takes three arguments: <version> <relation> <version>
Type dpkg --help for help about installing and deinstalling packages [*];
Use 'apt' or 'aptitude' for user-friendly package management;
Type dpkg -Dhelp for a list of dpkg debug flag values;
Type dpkg --force-help for a list of forcing options;
Type dpkg-deb --help for help about manipulating *.deb files;
Options marked [*] produce a lot of output - pipe it through 'less' or 'more' !
[+] INFO: Nothing to upgrade
```
```bash
henry@twilight ~ % ››› pacstall -Up
[+] INFO: Checking for updates
[+] INFO: Nothing to upgrade
```
> dpkg gives error when lt is quoted

- misc/scripts/install-local.sh
`dpkg-query -l "${breaks}"` also returns positive if status is `unknown ok not-installed`, or/and similar statuses
Change  the `dpkg-query` command to fix the false positives
> fix(install-local): `dpkg-query` false positives

- pacstall
There was extra padding in the `-h` option output.
Removes the excess padding.
> fix(main): Remove excess padding in `-h`

- misc/scripts/query-info.sh
Fixes #250
Use a combination of `numfmt` and `apt-cache` to generate the installed sizes of `-deb` pacscripts.
> feat(query-info): Ability to show size of `-deb`

- misc/scripts/search.sh
Specify from which repo to install for use in scripting
Add the possibility to specify from which repo to install before searching then with `pacstall -I package@user/reponame` for github and gitlab repos or `pacstall -I package@repourl` for other git-like repos.
Fixes #126
> feat(scripts): Ability to specify target repo when installing

- install.sh
- pacstall
- uninstall.sh
Currently our `ask()` is unable to read input which is piped into Pacstall. This greatly reduces scriptability. 
Modify `ask()` to accept input from pipe, and also do some cosmetic/QOL changes ( such as printing the piped input on the prompt etc ) when doing the same.
> feat(api): Make `ask()` read from pipe

- misc/scripts/search.sh
- pacstall
Add, fix and rework the messages for searching and downloading pacscripts
Add downloading message on the main script and replace `repo pacstall` with `official repo`. Fix the `if` statement in search related to this. Change the repo names from `user` to `user/repo` when searching.
> ref(search): Rework

- misc/scripts/upgrade.sh
During upgrade, pacstall will dump pacscripts in the current dir, and when upgrading later on in the same directory, pacstall will attempt to install the pacscript, which would be the old one
`cd` into `SRCDIR` on upgrade
> fix(scripts): fix clutter on download

- src/pacstall.py
The current message displayed on updating APT lists *incorrect* as it's not updating the system, instead only the APT lists.
Refactor the message to reflect this.
> ref(pacstall): Rename msg on updating APT list

- misc/scripts/install-local.sh
Fix `$breaks` check when re-installing or updating a package
Replace check's regrex to not split on `-`, only on spaces
> fix(install): Don't split on `-` while checking `breaks`

- misc/completion/bash
- misc/completion/fish
Fixes #371 
Instead of relying on the shell to expand the wildcards, this patch moves that job to the `find` command. This fixes the wildcard expansion issue in `fish`, and also gives us granular control over the expansions. Now only `-type f` (files) are suggested, whereas previously any directory name ending with `.pacscript` would also be suggested.
Turns out `-PK*` and `-KP*` flag completions were missing, added those.
> fix(completions): Broken completions

- misc/scripts/install-local.sh
Fix metadata logging not overwriting previous install metadate
Closes #392
> fix(install): add overwrite of metadata

- misc/scripts/install-local.sh
- pacstall
Keep build dir files of pacdeps when installation fails
Closes #373
> fix: `-K` flag on pacdep fails (keep build dir)

- install.sh
- misc/scripts/error_log.sh
- misc/scripts/install-local.sh
- misc/scripts/update.sh
- misc/scripts/upgrade.sh
- pacstall
When logging into some systems with a display manager, the `logname` command or `$USER` break sometimes due to unset variables usually handled by the DM.
Replace all instances of the previous commands with a single variable that tests for `logname` first (most reliable), then tries `$SUDO_USER`, then `$USER` finally.
> fix: inconsistent user account detection

- misc/completion/bash
Bash completions list all packages instead of filtering
Fix variable placement and remove the extra `"`s that break the `compgen` command
Closes #410
> fix(completions): bash completions not filtering packages

- pacstall
Fixes #412
Adds the missing error message in `-I` flag when no packages are specified.
> fix(pacstall): missing `-I` error message when no packages are specified

- pacstall
Fixes #407
Add missing `.pacscript` in the download message
> fix(pacstall): incorrect download message file path

- misc/completion/bash
Add missing case on bash completions
Closes #413
> fix(bash): missing `-T` completions

- misc/completion/bash
- misc/completion/fish
Fixes #415
Only `curl` `packagelist` when needed.
> perf(completions): stop `curl`ing `packagelist` needlessly

- pacstall
If a directory `$name` and `$name.pacscript` exist, and you attempt to run `pacstall -Il $name`, it would fail and report that `$name does not exist`
Add an extra check to the directory checker to ensure Pacstall won't `cd` into the directory `$name` if `$name.pacscript` exists
Fixes #408
> fix(pacstall): installation failure when a directory of the same name is present

- misc/completion/bash
Fix bash completions not working in some cases
Fix flag selection
Fixes #420
> fix(bash): completions not working when multiple flags are present

- misc/scripts/search.sh
Allows `-` in searches.
Put `--` in grep to prevent grep from thinking dashes are arguments.
Fixes #433
> fix(search): error when the query contains `-`

- misc/scripts/install-local.sh
- misc/scripts/remove.sh
Prevents the local dummy deb from being upgraded because of the higher priority of a repo.
Set the priority of `$name` to `-1`, which prevents all upgrades to that package.
> fix: prevent dummy deb from upgrading

- misc/scripts/add-repo.sh
- misc/scripts/download.sh
- misc/scripts/search.sh
- misc/scripts/upgrade.sh
- pacstall
To prevent bugs because of malformed input, like a dash, which would be evaluated by bash as a flag.
Add `--` before inputs so bash evaluates them as inputs instead of flags
> fix: miscellaneous possible bugs due to possible dashes in inputs

- misc/scripts/remove.sh
`return` does not exit removal if a package doesn't exist, but `exit` does.
Replace `return` with `exit`
> fix(remove): removal of unidentified packages

- misc/scripts/install-local.sh
Logs an error message when `$gives` contains multiple words by checking for whitespaces and commas.
Fixes issue #443.
Checks if `$gives` contains whitespace or commas.
Issue #443
> fix(install): ambiguous error message when `$gives` contains multiple fields

- misc/scripts/upgrade.sh
When upgrading, and you have a package not found in a repo, sed will give an error like this:
```bash
sed: couldn't open temporary file /var/log/pacstall/metadata/sedqIEaPr: Permission denied
```
Give it permission
Closes #446
> fix(upgrade): `sed` errors when package is non-existent

- pacstall
When the python rewrite gets merged into master, 1.7.1 will still try to
upgrade to the python rewrite, even though the locations of certain code
will not be there anymore. This adds a check to make sure Pacstall can't
upgrade to a pythonic version.
Check for the existence of `pyproject.toml`, and fail if it exists.
Update to this branch
Run `pacstall -U pacstall python3-rewrite`
> feat(update)!: prevent updating to an incompatible release

- misc/scripts/install-local.sh
Skips `hashcheck()` if the `hash` variable isn't present in the
pacscript.
Fixes #458 
Skips `hashcheck()` if `hash` variable isn't present in the pacscript.
> fix(install-local): skip hash check if not present

- pacstall/parser.py
The `upgrade` command parser fails when multiple arguments are specified.
Switch from `?` -> `*` [nargs](https://docs.python.org/3/library/argparse.html#nargs)
> fix(upgrade): error when specifying multiple args

- pacstall/cmds/download.py
Adds the missing `)` in the `OSError` error message.
> style(download): add missing `)`

- pacstall/cmds/download.py
- poetry.lock
- pyproject.toml
Increases speed of downloads from 5-6 secs to 3-4 secs.
Uses `anyio` to accomplish this (which is a dependency of `httpx`, therefore no additional dependencies required to achieve this).
> perf: remove dependency on `aiofiles`

- misc/scripts/install-local.sh
`dpkg` currently cannot install dependencies, it can only check for them, so unless the dependencies have already been installed beforehand, the dummy deb will fail to install.
Replace `dpkg` with `apt-get` in order to install dependencies from the deb
https://github.com/pacstall/pacstall-programs/pull/703
> fix(install-local): install dependencies from deb

- misc/scripts/query-info.sh
When `numfmt` is given a blank input, it freezes, which can be observed by running `numfmt --to=iec`. The package `git-delta-deb` package contains no size variable, so `numfmt` is given no input, causing the freezing.
Move `numfmt` so it is piped into, instead of given input. Then if the `size` variable is empty, replace it with the text `invalid` to show the user
Fixes #442
> fix(query-info): frozen `-Qi` when deb contains no size variable

- misc/scripts/remove.sh
Removes dummy deb without interaction
Adding `-y` to the arguments for `apt`
https://discord.com/channels/839818021207801878/866673569521991700/943956875307778051
> fix(remove): purge without user input

- misc/scripts/install-local.sh
When installing the dummy deb, a git commit id can mess with the versioning, and some commits will be seen as a downgrade to apt.
Allow downgrades
> fix(install-local): allow apt to downgrade packages

- misc/scripts/install-local.sh
Fixes #499 
Split `build_dependencies` and properly purge everything.
> fix(install): properly purge build dependencies

- misc/scripts/install-local.sh
Fail if `optdepends` key's do not have a description, and cut to correct character.
Check the keys with a for loop.
Fixes #507
> fix(install-local): error out if optdepends has no description

- README.md
We don't have 175 packages in our repo any more, so the number is inaccurate at first glance, as well as reword what auto updates mean for git packages
Towards the end of [this video](https://www.youtube.com/watch?v=RYaHaxcv7Gg&ab_channel=atareao), he mentions this information.
> docs(readme): remove inaccurate package count and reword "auto updates"

- pacstall
The install-local command didn't accept paths to pacscripts since a bug introduced in #97
Fix `cd` into the pacscript directory and the file checks
> fix: accept paths with `-Il` command

- misc/scripts/search.sh
Currently `search.sh` uses `return` instead of `exit` to signify a non existent package, but that doesn't work, which gives an exit code of zero instead of one.
Replace certain `return`s with `exit`s
> fix(search): fail out on no package

- README.md
- pacstall
Allows http code 301 (moved permanently). This is most notably seen with github clone URLs as seen below
```
$ curl -o /dev/null -s -w "%{http_code}\n" -- https://github.com/pacstall/pacstall.git
301
```
> fix(check_url): add http code 301 to permitted list

- misc/scripts/install-local.sh
Fix for the upgrade command of some `-deb` packages installed through pacstall, which were unable to upgrade due to the `$breaks` variable
Skip $breaks check if package already installed
> fix(install-local): skip `$breaks` check for  `-deb` upgrades

- misc/scripts/install-local.sh
Fixes #512 
Move the patch downloader above the package downloader
> fix(install-local): download patches before downloading package

- misc/scripts/install-local.sh
Check if pacdep is already installed and skip if that's the case
Add check and warning messages
Closes #539
> fix: check if pacdep is already installed

- misc/scripts/install-local.sh
- misc/scripts/upgrade.sh
Many places in the codebase call unnecessary `sudo`s 
It removes the offending `sudo`s.
> fix: remove useless sudos

- uninstall.sh
Fixes a bug where Pacstall doesn't uninstall the packages when the user chooses to do so.
> fix(uninstall): package uninstallation

- pacstall
Currently we check `github.com` twice on failure, this is unnecessary.
Check `gitlab.com` instead on failure.
> fix(pacstall): check gitlab on `check_url` failure

- misc/scripts/install-local.sh
Fix pacdep message on upgrade
Rework the pacdep install checks and messages
> fix: messages on pacdep install/upgrade

- misc/scripts/install-local.sh
We don't need to check `$replaces` if the package is already installed. This is happening during reinstall and upgrade.
> fix(install-local): skip `$replace` check if package is already installed

- pacstall
> fix(pacstall): missing `-T` flag in help section

- misc/scripts/install-local.sh
The original `set -euo pipefail` PR (#543) implemented only `set -e`.
Add missing flags when calling bash subprocess
#537
> fix(install-local): Replace `-ce` with `-ceuo pipefail`

- pacstall
When #543 was introduced, all variables not exported would be unusable inside pacscripts, including the DISABLE_PROMPTS variable.
Export it.
Fixes bug in of #543.
> fix(pacstall): export `DISABLE_PROMPTS`

- misc/scripts/add-repo.sh
- misc/scripts/download.sh
- misc/scripts/search.sh
- pacstall
Add support for locally hosted repos
Use `curl` instead of `wget` due to it's  `file://` protocol support. Format path  in `add-repo` when adding local repos.
> feat!: support for local repos

- misc/scripts/remove.sh
https://github.com/pacstall/pacstall/blob/08501b9cf793521ef23f743eb0fe0a795f471aca/misc/scripts/remove.sh#L88 doesn't actually source the file, meaning removescript always fails.
Source it.
> fix(remove): source pacscript before running removescript

- misc/scripts/install-local.sh
- misc/scripts/remove.sh
- pacstall
Currently `fancy_message` can get very hard to read very fast. This PR will split up a couple previous `fancy_message`s into a submenu styled approach.
@wizard-28 for helping design the UI
> feat: add `fancy_message sub` for cleaner output

- misc/scripts/install-local.sh
Currently, if an `optdepends` array contains an invalid package name, Pacstall will attempt to install it if the user confirms they want to install `optdepends`. This PR will make Pacstall check for the existence of all the `optdepends` before presenting the user with the choice to install them, and will filter out and warn the user of any incorrect packages.
Use `apt-cache search` to confirm package existence.
> feat(install-local): warn user if optdepend does not exist in repos

- misc/scripts/install-local.sh
Showing the index of each optdepend looks very visually appealing and can make it easier to differentiate between lines (maybe it's my dyslexia, who knows).
> feat(install-local): show pretty index of optdepends

- misc/scripts/install-local.sh
A typo causes pacstall to create a file called `t` in the CWD.
Don't create the file.
> fix(install-local.sh): do not create random file `t`

- misc/scripts/install-local.sh
- pacstall
Currently, `optdepends` can either be entirely selected or entirely deselected, leaving the user with no choice of what optional dependencies they want to install.
Create a prompt that will ask the user which `optdepends` they want to install, or choosing ranges (`2-5`), while also keeping `Y` and `N` options as to select everything or nothing.
> feat(optdepends): add array selection

- misc/scripts/install-local.sh
Suppose you have the build dependencies `libdbus-1-dev dbus`, however dbus is already installed. Pacstall will go through and remove packages from `build_depends` based on if they are installed or not. So, Pacstall will try to remove `dbus` from the deps, as it's already installed, however it will try to remove the first time it sees the string `dbus`, instead of the package, so the final result is `lib-1-dev dbus`. This fix internally changes `build_depends` to an array and loops through it to remove already installed elements.
> fix(build_depends): remove packages from installation by full name

- misc/scripts/install-local.sh
Currently, only debs can make use of `gives`. This PR makes it so that any package can be installed under a name besides whats declared in `$name`.
> fix: all packages can use `gives` now

- misc/scripts/install-local.sh
A bug that only includes the first optdepend in suggests.
> fix(suggests): include every optdepends

- misc/scripts/install-local.sh
Currently inputing invalid numbers into `prompt_optdepends` will just be skipped over entirely instead of giving a warning.
> fix(prompt_optdepends): add guard to max optdepend

- misc/scripts/install-local.sh
Remove never used function. I don’t even remember why we included it, although I’m pretty sure it was supposed to be used in pkgver, but we never encouraged or even told anyone about the function.
https://github.com/pacstall/pacstall/commit/00714853217ee83273d108c9136dcf57165d1ed5
> rm(cget): remove never used internal function `cget`

- misc/scripts/install-local.sh
When installing a package with `gives`, the `makedeb` function will print out:
```bash
[+] INFO: Packaging foo-git
```
Now becomes
```bash
[+] INFO: Packaging foo-git as foo
```
> fix(makedeb): print gives first

- misc/scripts/install-local.sh
Some variables in functions are not localized, meaning they are accessible throughout the entire script, when they should not be. Also fixed a bug that would remove `$name`, when it should be `${gives:-$name}`.
> fix(install-local): localize some variables, fix pacstall dep bug

- install.sh
- misc/scripts/search.sh
- misc/scripts/upgrade.sh
To remove a dependency we only use 3 times.
Instead of using `awk` to print the input `bc` needs, just use `awk` to do the work.
> rm(bc): remove bc dependency

- misc/scripts/install-local.sh
Some parts of the codebase use `grep`, but we can replace them with faster bash comparisons.
> fix(install-local): move some `grep` commands to bash comparisons

- misc/scripts/install-local.sh
- pacstall
Debconf will use prompts. `-P` guarantees no prompts. Export `DEBIAN_FRONTEND` as `noninteractive` to guarantee no prompt.
> fix(-P): use noninteractive

- misc/scripts/install-local.sh
If `PACSTALL_EDITOR`s command is not found, pacstall will pass through. This will make it fall back to `EDITOR`.
> fix(PACSTALL_EDITOR): fall back to EDITOR if not found

- misc/scripts/install-local.sh
Currently some scripts have methods of preventing running on certain distros using this codeblock:
```bash
if [[ "$(grep -Po 'ID=\K[^"]+' /etc/os-release)" == "debian" ]]; then
fancy_message error "This script doesn't work on Debian"
cleanup # Trigger pacstall cleanups
exit 1
fi
```
This is not the best as it triggers functions that should really only be called in pacstall, it clutters the script, it doesn't take into account version differences, etc. It also prevents some CIs from sourcing this at all.
Add a built in method with a new array called `incompatible`. Each key should look like this: `$distro:$version_name`. This will declutter a lot of scripts, and make it easier to fine tune Pacscripts. Globs also work. This will mean that a Pacscript has no running components when sourced …
> feat: add `incompatible` array

- misc/scripts/install-local.sh
Some packages may want to force an up/downgrade.
Add the `epoch` variable.
```bash
${epoch+$epoch:}$version
```
Consider this code. What the `${epoch+$epoch:}` will do is check if `epoch` exists, and if so, print `$epoch:`, and if it does not exist, it will simply not print anything, leaving us with just `$version`. Note the `:`. It is how apt detects epochs.
> feat: add `epoch`

- misc/scripts/install-local.sh
We set an apt pin in order to prevent apt from overwriting packages when we update apt. The problem is that we currently set the pinned package to `name`, which might be different than `gives`, meaning that if `gives` is a valid apt package **and** is upgradable in the repos, the pin will not work.
Install `exa-git`, then run `sudo apt update`. Observe that apt wants to upgrade.
> fix(pin): use gives first

- .github/FUNDING.yml
Delete the overriding funding config, to follow the organization default one.
> chore(funding): delete overriding funding config

- misc/scripts/install-local.sh
- misc/scripts/upgrade.sh
If a package does not start with a number, Pacstall will prepend a `0` to it, however that is problematic for git package sha's.
Install `exa-git`, then upgrade it.
Add a clause to allow first letter in git packages.
> fix(upgrade.sh): skip git packages if `0$version` equals `$remoteversion` without `0`

- misc/scripts/install-local.sh
`gzip` is singlethreaded, and does not compress that well. `xz` on the other hand compresses a lot more, and it multithreaded.
> **Note**
> Both Ubuntu and Debian have `xz-utils` installed by default
Compress `{control,data}.tar` with the `xz` format instead of `gz`.
The benchmarks for `xz` were not performed with the `-e` flag, which compresses further. The results from `-e` take too long for a marginally better or sometimes worse size.
| Package | Raw size | gzip (-9n) | xz (-9 -T0) | zstd (-19 -T0) |
|---------|----------|------------|---------|--------------------|
| pacup-bin | 32MB | 12.8MB | 9.6MB | 10.2MB |
| neovim | 9.97MB |  9.9MB | 7.1MB | 7.8MB |
| discord | 73MB | 73.6MB | 53.4MB | 58.8MB |
| pacstall | 63.2KB | 24.1KB | 21.5KB | 22KB |
| hyperfine-bin | 976KB | 968KB | …
> feat(createdeb): use `xz` instead of `gzip`

- misc/scripts/install-local.sh
`gives` is needed on Debs to get the actual apt package name. If it does not exist, Pacstall will try to remove debs with the apt name `name`, which most definitely is not the canonical name. 
Figure out the package name anyways and warn the user.
Fixes #736
> fix(log): figure out what `gives` is based on Deb

- misc/scripts/upgrade.sh
Currently we run multiple upgrade checks at once, but without subshelling, and without a proper catch-all wait command, meaning that some packages will randomly not be shown for upgrading, even though they are.
Add subshelling and proper catch-all `wait`. This will guarantee that all checks finish.
> fix(upgrade): place wait to prevent overwritten variables

- misc/scripts/install-local.sh
- misc/scripts/remove.sh
Currently, we remove any pacdep if the parent package is removed, however this does not take into account if other packages depend on the pacdep. This PR makes sure that apt knows that the pacdep is a dependency instead of a package that was installed and happened to satisfy the dependency.
`apt-mark auto` it.
> fix(pacdeps): mark pacdep as auto installed

- misc/scripts/install-local.sh
Currently if hashcheck fails, it returns, not exits out.
> fix(hashcheck): use exit instead of return

- misc/scripts/install-local.sh
If the user wants to set nproc to something other than max cores.
Create a function which overrides it.
Fixes #382.
> feat(build): add `PACSTALL_BUILD_CORES` variable

- misc/scripts/install-local.sh
- misc/scripts/remove.sh
PPAs linger after a package is removed that depended on a PPA.
Remove them in `remove.sh` and convert the `_ppa` string into an array.
> fix(ppa): add dangling PPA warning

- pacstall
We are grepping our own `-Qi` output, instead of sourcing the metadata file.
> fix(-V): properly figure out version

- misc/scripts/install-local.sh
Move `optdepends` to `Suggests` and install them afterwards.
Change some variable names in order to make `prompt_optdepends` readable.
Remove `prompt_optdepends` entirely when using `-B` flag.
Install optdepends before package builds (now can specify buildtime optdepends)
> fix(prompt_optdepends): prevent only adding non-installed pkgs to suggests

- misc/scripts/install-local.sh
Currently some arrays are used like this: `${foo[*]}`. which means that they will resplit elements. The better way is this: `"${foo[@]}"`, which will quote them as to not resplit every element.
> Quoting an expansion of an array through the @ index makes Bash expand that array into a sequence of its elements, where each element is wrapped in quotes.
http://mywiki.wooledge.org/BashGuide/Practices#Quoting
> fix(arrays): quote and split

- misc/scripts/install-local.sh
Currently we set `homedir` to `/home/$USER`, but this can be an issue when users *could* in theory set their homedir to something else.
```bash
henry@plasma:~$ echo ~root
/root
henry@plasma:~$ echo ~henry
/home/henry
henry@plasma:~$ echo ~games
/usr/games
henry@plasma:~$ echo ~irc
/run/ircd
```
vs setting the assumed homedir to `/home/$USER`.
This approach has one drawback and that is that is forces the Deb's post{rm,inst} running shell to be bash, not sh, however this isn't such a big deal considering that you have to have bash installed to run Pacstall, and most systems that a `-B` Deb is being installed on should have it as well.
Use the `~$USER` bashism to get the canonical path to any given usernames homedir.
> fix(homedir): detect any home dir, not just /home

- misc/scripts/install-local.sh
- pacstall
It serves no purpose to call an external command when a builtin bash variable does the exact same thing.
> ref(pwd): `pwd` -> `$PWD`

- misc/scripts/install-local.sh
Take this code piece into consideration:
```bash
optdepends=("viu: image preview" "lshw: hardware info")
```
and that `lshw` is installed, and `viu` is not in the repos. Pacstall will not show a warning that `viu` is not in the repos because `prompt_optdepends` only delivers a prompt when anything in `optdepends` are not installed, and `lshw` is, and `viu` is added to the `missing_optdeps`, so that won't be shown either, leading to no prompt, and no shown messages.
Run the showing of missing optdepends before the check for `suggested_optdeps`.
> fix(prompt_optdepends): always show missing optdeps

- misc/scripts/install-local.sh
- misc/scripts/query-info.sh
Somewhere along the road, `$size` stopped working in `query-info.sh`. Another bug this fixes is the `Installed-Size` field including the path of `/usr/src/pacstall/$name`.
> fix(query-info): add back size

- misc/scripts/install-local.sh
Currently only pacdeps that are not `-deb` can be marked as auto due to the separate installation processes.
Add a check in the deb installation.
> fix(deb): make deb pacdeps auto

- pacstall
Some CIs have to either remove or bypass the axel binary because of explosive output when downloading. This PR introduces the `PACSTALL_DOWNLOADER` variable which will allow either `axel` or `wget` in order to forcibly set the downloader.
> feat(download): `PACSTALL_DOWNLOADER` variable

- pacstall
Rhino's logs reach 500MB because of the download progress bars...
> feat(download): add `quiet-wget` for silent download (#786

- misc/scripts/install-local.sh
If some variables are not cleaned out, they can leak into others, which happened after updating steamtinkerlaunch-git, then rhino-pkg-git. The `postinst` was leaked into rhino-pkg-git when it had none, resulting in an install error.
I went through the Pacscript 101 wiki and made sure everything was cleaned.
> fix(cleanup): unset all variables during life of pacscript

- misc/scripts/install-local.sh
`pkgver` leaks into `compare_remote_version()`, causing potentially broken information.
Unset `pkgver` before running.
> fix(compare_remote_version): unset `pkgver` before checks

- misc/scripts/install-local.sh
The issue is that a pacdep file isn't being deleted once it's not used.
Remove it..
> fix(pacdeps): remove pacdep file after pass

- misc/scripts/search.sh
It's one less external tool used.
Replace `tr` in `search.sh` with a native bash variable substitution.
> perf(search): use native find replace

- misc/scripts/search.sh
Remove `grep` from `search.sh`
Use `awk` instead
> ref(search): replace grep+cut+awk with awk

- misc/scripts/install-local.sh
During installs with multiple packages, it can be hard to see what package is currently being installed.
Show the package name before and after it installs.
> feat(install-local): show package name at beginning and end

- pacstall
Allow format `username:branch` when updating to a dev branch
Rework the persistent updates checks
This is how we should be doing before anyway
> feat(main): allow format `username:branch` for updates

- misc/scripts/install-local.sh
The function is one of the oldest and hasn't been touched in a long time. It has some quoted and some not quoted variables, and it uses a sed command that can easily be replaced.
Quote all variables, swap out sed for native bash parameter expansion.
> refactor(install-local): quote everything, remove sed command

- misc/scripts/install-local.sh
Parts of the codebase are duplicates, and a couple references to `/tmp/pacstall` should be `SRCDIR`.
> fix(install-local): remove duplicate code, use `SRCDIR`

- misc/scripts/install-local.sh
- misc/scripts/upgrade.sh
- pacstall
Ok this PR solves not only the rhino CI issue, but it's something I'll be doing more often, which is trying to remove all the sudos in the code that really don't need to be here.
`SRCDIR` stay's user owned and is created without sudo, and *only* removed with sudo because of pacscripts calling sudo.
> fix(SRCDIR): create without sudo

- misc/scripts/install-local.sh
Previously we'd check if deps exist first, then if pacdeps exist, then make them implicit deps, but we don't want that. We want to check if pacdeps exist, then add them to the deps list.
> fix(pacdeps): pacdeps are implicit deps to parent package

- misc/scripts/install-local.sh
- pacstall
Adds `PACSTALL_PAYLOAD` environment variable support, that skips downloading the `url`. This is to prevent double downloads when using pacup.
Adds `PACSTALL_PAYLOAD` environment variable support that takes a file path as the value. This disables the `download` function, and makes `install-local.sh` use the `/tmp/pacstall/<file_name>` as the file name, were the payload is copied to.
> feat(pacstall): add `PACSTALL_PAYLOAD` support

- misc/scripts/add-repo.sh
- misc/scripts/install-local.sh
- misc/scripts/query-info.sh
- misc/scripts/search.sh
- misc/scripts/upgrade.sh
- pacstall
Safety:tm: by using `mapfile` to convert a string at a delimiter instead of relying on bash to do it, and also by quoting variables. 
This also fixes `select_options` to allow for complex stuff like `1..3 5-10` which it should have been able to since the beginning.
> refactor: quote variables & use `mapfile` wherever possible

- misc/scripts/install-local.sh
Some packages may want to use a preinstall function before the deb is installed.
Add a clause to add `preisnt`.
> feat: add `preinst` function

- misc/scripts/install-local.sh
Explicitly chosen `optdepends` are not counted in `Depends`.
Add them.
> fix(deps): explicitly chosen optdepends are Depends

- misc/scripts/install-local.sh
Grep and Awk are slow.
Swap out Grep with native Bash globs, and replace Awk with `cut`.
> perf(install-local): use cut instead of awk, use bash globs instead of grep

- misc/scripts/error_log.sh
- misc/scripts/search.sh
- pacstall
Some variables can easily be removed after use by just adding `local` to the front in functions, which might help reduce variable collision in Pacscripts.
> fix: localize as many vars as possible

- misc/scripts/install-local.sh
`deps` may not exist, such as if a package has `pacdeps` but no `depends`.
> fix(pacdeps): also check if `deps` no exist

- pacstall
`5..1` doesn't make sense as a range, and it messes with `seq`.
Check if `range[0] > range[-1]` and fail if so.
> fix(select_options): only allow ranges from smallest to greatest

- pacstall
> fix(select_options): ranges cannot go from num to num

- misc/scripts/upgrade.sh
Pacstall v3.9.0 errors out when upgrading any package.
Removes quotes surrounding L29, fixing the issue.
> fix(upgrade): numeric argument bug

- misc/scripts/install-local.sh
Single line descriptions are very limiting, and the maintainer may wish to expand on it.
If `description` is longer than a single line, we loop over and make an array. Then we can print out the first line normally, and for every line after, we print it with a preceding space (control file stuff). Blank lines are denoted by a single period on the line.
> feat(pacscript): allow long descriptions (#860

- misc/scripts/install-local.sh
- pacstall
Right now it's kind of confusing (according to some).
Replace `..` with `-`, remove the `fancy_message` `[Y/n]` stuff, add explicit part in optdepends print out for skipping, and add `or` text between range and `Y`
> fix(select_options): make everything more explicit

- pacstall
Fixes payload bug, where it'd delete the file before processing it.
Check if we're in payload mode, and proceed accordingly
> fix: only delete stuff if not in payload mode

- misc/scripts/install-local.sh
If a URL ends in `.appimage`, the checker will be searching for `AppImage` which won't work.
Just for the package type checker, lowercase the entire URL to check for the ending.
> fix(download): convert to lowercase for ending check

- misc/scripts/install-local.sh
- pacstall
`depends="foo bar baz"` looks really bad and is more prone to errors than `depends=("foo" "bar" "baz")`. This changes `depends`, `build_depends` and `breaks` to arrays (most are already turned into arrays internally, so this isn't a big change internally).
Add a check to convert the key to an array if it's not an array already, and do nothing if it's already an array. This check makes it not a breaking change, although we could add a warning if it is a variable.
> feat(pacscript): change needed variables to arrays

- misc/scripts/add-repo.sh
- misc/scripts/install-local.sh
- misc/scripts/search.sh
- misc/scripts/update.sh
- misc/scripts/upgrade.sh
- pacstall
Because we can and it looks cleaner.
> refactor(*): combine multiple checks

- misc/scripts/install-local.sh
It's faster, we don't have to call an external command.
Replace `$(tput bold)` with raw ASCII code.
> fix(post_scripts): use raw ascii code instead of tput

- pacstall
`$2` is an argument to `trap_ctrlc`, not the global pacstall `$2`.
Use `$PACKAGE`, or fall back to the string `package` if `$PACKAGE` was not defined when killed.
> fix(trap_ctrlc): `$2` is not the global one, it is the argument

- pacstall
If we don't initialize it first, we can't compare with it with `(( ))`.
> fix(install): initialize `PACSTALL_INSTALL`

- misc/scripts/add-repo.sh
- misc/scripts/install-local.sh
- misc/scripts/query-info.sh
`tr` is an external command, and we can easily speed it up by using pure bash alternatives.
> perf: remove instances of `tr` in favor of pure bash

- install.sh
- misc/scripts/install-local.sh
- misc/scripts/query-info.sh
- misc/scripts/update.sh
- misc/scripts/upgrade.sh
- pacstall
- uninstall.sh
It's fragmented between `NORMAL` and `NC`, and `NC` is faster because it's a raw ascii code.
> refactor(*): remove `NORMAL` variable

- misc/scripts/install-local.sh
It's not practical to run subshells to get the core count.
Create a readonly global variable called `NCPU` (Number *of* CPUs).
```bash
name="hello"
repology=("project: ${name}")
version="2.12.1"
url="https://ftp.gnu.org/gnu/${name}/${name}-${version}.tar.gz"
build_depends=("build-essential")
depends=("libc6")
breaks=("${name}-git" "${name}-traditional")
replace=("${name}")
description="GNU implementation of the classic program that prints 'Hello, world!' when you run it"
hash="8d99142afd92576f30b0cd7cb42a8dc6809998bc5d607d88761f512e26c7db20"
maintainer="WRM-42 <y8bsbahy@anonaddy.me>"
build() {
./configure
make -j"${NCPU}" # Previously $(nproc)
}
install() {
sudo make install DESTDIR="${pkgdir}"
}
```
> feat(pacscript): add `NCPU` variable bound to `nproc`

- misc/scripts/remove.sh
Because apt is stupid and """"removing"""" a package won't register it with apt unless it's purged 🙄.
> fix(remove.sh): purge instead of remove

- misc/scripts/remove.sh
We shouldn't log a failed package removal if it doesn't exist at all. We still log if it does exist and fails to remove.
> fix(remove.sh): we do not need to log simple stuff

- misc/scripts/install-local.sh
- pacstall
Because we can and it's builtin rather than not.
> refactor(*): use `printf` instead of `date`

- misc/scripts/install-local.sh
It looks weird for this to show:
```bash
[+] INFO: Packaging goverlay as goverlay
```
when:
```bash
[+] INFO: Packaging goverlay
```
would be fine, but only when `$name` and `$gives` are the same (but then at that point, the pacscript maintainer should drop `$gives` and let `$name` implicitly be `$gives`.)
> chan(makedeb): do not show packaging status if $name and $gives are the same

- pacstall
Original issue: `rhino-core` received a dependency update for `unicorn-desktop`, but `unicorn-desktop` was added to the repository after the previous `rhino-core` update. As a result, `-Up` fails to update `rhino-core` from beta4 to beta5, and an `-I` to fetch the repo must be done to update.
After looking into it, we found that `$URL` is getting eaten up by something, and not outputting correctly. We have found this fix to work, which subsidizes the repo into the `$URL` directly.
Chances are we will need to revert this later, once we find where it is being eaten up, and making proper fixes. Because this is a fix vital to the user experience, it is necessary to push a fix out quickly, but it is recognized that this is not the best solution, and will have to be re-patched in the future.
> tempfix: force set `$URL` to repair `-Up` function

- pacstall
Because apt is stupid and if a package is removed but not the config, it says it's installed.
> fix(is_apt_package_installed): accurately check install status

- misc/scripts/install-local.sh
We only allowed top-level directories in debs, and we would simply ignore files. Even though people should not be putting files in `/`, it should be there for them to use regardless.
> fix(createdeb): allow top level files

- misc/scripts/install-local.sh
- pacstall
`install` is a command and also a function that we use, and the only reason we can get away with this is because sudo won't run functions, meaning that `sudo install` in the `install` function will run the command. That's hacky. Plus we can get closer to PACBUILD and Pacscript convergence with `package()`.
> feat(install): add `package` func to replace `install`

- misc/scripts/install-local.sh
We have `incompatible` to prevent installation on certain systems, but we don't have a way of accessing the current systems information to easily structure an install to certain systems.
Add `$DISTRO`, which is formed as `${distro_name}:${distro_version_name}`. Mine for instance would be `ubuntu:kinetic`.
> feat(pacscript): add `DISTRO` variable

- misc/scripts/install-local.sh
- pacstall
Currently `-L` looks so barren. This basically merges the looks of `-Qi` with the functionality of `-L`.
We check if the terminal is a terminal or is being piped. We display the old `-L` output when it's being piped as it just displays package names, but if it's an interactive terminal, we show the new style in all it's glory.
> feat(-L): add fancy listing

- misc/scripts/error_log.sh
- misc/scripts/install-local.sh
`$(date)` is way slower than `printf '%()T'`, which is a builtin.
Replace them with equivalent calls.
> refactor(date): replace subshell calls to `date` with `printf`

- misc/scripts/install-local.sh
- misc/scripts/query-info.sh
- pacstall
Currently we have one way to get information about an installed package in a parsable way, and that's `-Qi`. We also have `-V pkg` for getting the version but that's never been publicly used and not meant for people to actually use. This PR adds an extra argument to `-Qi` that will print out the corresponding key:
```bash
elsie ~ % ››› pacstall -Qi goverlay
name: goverlay
version: 0.9.1
size: 30K
description: Graphical UI to help manage Linux overlays
date installed: Sat May 13 18:33:06 CDT 2023
maintainer: Elsie19 <hwengerstickel@pm.me>
dependencies: mangohud libqt5pas-dev
install type: explicitly installed
elsie ~/Elsie19 % ››› pacstall -Qi goverlay install_type
explicitly installed
elsie ~/Elsie19 % ››› pacstall -Qi goverlay version
0.9.1
elsie ~/Elsie19 % ››› pacstall -Qi goverlay …
```
> feat(-Qi): add queries

- misc/scripts/query-info.sh
Because a subshell is too slow.
> perf(-Qi): use name references instead of subshells

- pacstall
Because we only use it in one place and it's quicker than calling a function.
> refactor(pacstall): inline `size_of_deb`

- misc/scripts/install-local.sh
If for some reason a developer makes a really bad pacscript, and keys in `pacdeps` are not one word, it can lead to incorrect logging.
We can use `declare -p` to print out how bash views the array, which is almost guaranteed to be safe from splitting, and can be sourced.
> fix(log): use `declare` to avoid possible string splitting

- install.sh
- misc/completion/bash
- misc/completion/fish
- misc/scripts/dep-tree.sh
- misc/scripts/error_log.sh
- misc/scripts/install-local.sh
- misc/scripts/query-info.sh
- misc/scripts/remove.sh
- misc/scripts/update.sh
- misc/scripts/upgrade.sh
- pacstall
Because apparently some apps clear out our metadata.
Split `LOGDIR` into:
- `LOGDIR`: `/var/log/pacstall/error_log/`
- For logging errors
- `METADIR`: `/var/lib/pacstall/metadata/`
- For metadata
Closes #406.
> fix(logdir): split `LOGDIR` into `LOGDIR` and `METADIR`

- pacstall
Because we just want to exit, and not show anything to the program trying to access the package list.
Check for `[[ -t 1 ]]`.
> fix(-L): hide no install error on non-interactive

- misc/scripts/install-local.sh
the is_compatible_arch check doesn't currently work for foreign architectures - i.e. if dpkg adds arm64 to an amd64 machine, CARCH won't do, so we need a solution.
Make a FARCH variable array, test if it exists, and test if our input arch matches one of the FARCH outputs
> fix(pacstall): add `FARCH` array

- misc/scripts/install-local.sh
It's slow and at the beginning of every pacstall run, it checks if the cache is reasonably in date (7 days), so regenerating the cache for checking `optdepends` is really slow and not useful.
Add `--no-generate` to `apt-cache`.
> perf(prompt_optdepends): do not regen cache on every apt-cache run

- misc/scripts/install-local.sh
We should block the package name and everything it provides in the pin.
Check `man 5 apt_preferences`. Basically the `Package` section allows us to specify multiple packages per pin by using a space delimited list.
> fix(pin): include `provides[@]` in pinning

- misc/scripts/install-local.sh
- misc/scripts/upgrade.sh
It fudges up the version, like [spotify-client-deb](https://github.com/pacstall/pacstall-programs/blob/f46dd0a27d56267acd8499a078004c95c7303d2a/packages/spotify-client-deb/spotify-client-deb.pacscript) is `1.2.13.661.ga588f749-pacstall1` when it should be logged as `1.2.13.661.ga588f749`.
> fix(full_version): use old style for debs

- misc/scripts/upgrade.sh
The fix was pre-4.0.0 and since we use `pkgver` as a var for the tag, we don't need this.
> fix(upgrade): remove pre-4.0.0 git versions

- pacstall
Because it spams the console during `-Up`.
Redirect stderr output.
> fix(getMasks): redirect pipe output

- pacstall
When looking for errors with Pacstall, we like to `set -x`. However, it is often confusing exactly which location/file each line is coming from.
Add Elsie's custom PS4 prompt that increases debug verbosity to point to where execution is occurring
> fix(pacstall): declare verbose debug output

- misc/scripts/search.sh
Because `i` in `upgrade.sh` is being overwritten by `i` in `search.sh`.
> fix(search.sh): use different variable name

- misc/scripts/add-repo.sh
- misc/scripts/search.sh
> perf(search): use `printf -v` instead of subshells

- misc/scripts/install-local.sh
The Unix philosophy is documented by [Doug McIlroy](https://en.wikipedia.org/wiki/Doug_McIlroy)[[1]](https://en.wikipedia.org/wiki/Unix_philosophy#cite_note-taoup-ch1s6-1) in the Bell System Technical Journal from 1978:[[2]](https://en.wikipedia.org/wiki/Unix_philosophy#cite_note-2)
1. Make each program do one thing well. To do a new job, build afresh rather than complicate old programs by adding new "features".
2. Expect the output of every program to become the input to another, as yet unknown, program. Don't clutter output with extraneous information. Avoid stringently columnar or binary input formats. Don't insist on interactive input.
3. Design and build software, even operating systems, to be tried early, ideally within weeks. Don't hesitate to throw away the clumsy parts and …
> fix(install-local.sh): repair `FARCH` array

- misc/scripts/checks.sh
- misc/scripts/install-local.sh
Oren (that's me) has been annoyed when creating packages that only work on a very specific distro version, having to provide a scroll's worth of listings in the `incompatible` array. 
To solve this, a `compatible` array now exists, which is basically just the inverse of `incompatible`. `compatible` will always take precedence, because it is implied that anything not listed is `incompatible`. This adds checks to make sure compatible array is checked first, and if both of them are provided, it will give an error.
> feat(install-local.sh): add `compatible` array

- misc/scripts/install-local.sh
Before (true positive):
```bash
+ compatible=("ubuntu:devel")
+ get_compatible_releases ubuntu:devel
++ lsb_release -si
+ local distro_name=Ubuntu
+ distro_name=ubuntu
++ lsb_release -ds
++ tail -c 4
+ [[ xi) == \s\i\d ]]
++ lsb_release -sc
+ local distro_version_name=devel
++ lsb_release -sr
+ local distro_version_number=2023.3
+ input=('ubuntu:devel')
+ local input
+ for key in "${input[@]}"
+ [[ ubuntu:devel == \*\:* ]]
+ [[ ubuntu:devel == *\:\* ]]
+ [[ ubuntu:devel == \u\b\u\n\t\u\:\d\e\v\e\l ]]
+ return 0
```
Before (false negative):
```bash
+ compatible=("ubuntu:mantic" "ubuntu:devel")
+ get_compatible_releases ubuntu:mantic ubuntu:devel
++ lsb_release -si
+ local distro_name=Ubuntu
+ distro_name=ubuntu
++ lsb_release -ds
++ tail -c 4
+ [[ xi) == \s\i\d ]]
++ lsb_release -sc
+ …
```
> fix(install-local.sh): repair `compatible` array

- .pre-commit-config.yaml
- misc/scripts/install-local.sh
- misc/scripts/search.sh
- pacstall
Currently, pacdeps are being installed from the main repo if they exist there instead of giving preference to the same repo as the package being installed
Check if the pacdep exists in the same repo as the package that requires it and install from it if it exists
Closes #680
> fix: install pacdeps from the same origin

- misc/scripts/search.sh
We don't have a need for the subshells.
Replace them with `<<<` variable redirection.
Also, I replaced `readlink -f` with `realpath` which seems to be faster based on my testing.
I also removed a leading glob where there shouldn't be one.
> perf(search): remove mapfile subshells

- misc/scripts/upgrade.sh
Fixes the issue where the metadata logging for pacdeps doesn't log `_remoterepo` properly on upgrades.
Add the missing `$REPO` export on `upgrade.sh`;
There should have been opened as an issue, but it seems Elsie didn't do it smh my head
> fix(upgrade): Missing export for pacdep metadata logging

- misc/scripts/error_log.sh
- misc/scripts/install-local.sh
Stupid bug comes up because LOGDIR isn't properly checked to be created
```bash
[~] rhino-live@rhino-live $ pacstall -PI pacstall-qa-git
[*] WARNING: Prompts are disabled
(pacstall-qa-git) Do you want to view/edit the pacscript? [y/N] N
[+] INFO: Sourcing pacscript
[+] INFO: Installing nushell-bin
[*] WARNING: Prompts are disabled
(nushell-bin) Do you want to view/edit the pacscript? [y/N] N
[+] INFO: Sourcing pacscript
[+] INFO: Retrieving packages
Initializing download: https://github.com/nushell/nushell/releases/download/0.86.0/nu-0.86.0-aarch64-unknown-linux-gnu.tar.gz
File size: 26.9117 Megabyte(s) (28218916 bytes)
Opening output file nu-0.86.0-aarch64-unknown-linux-gnu.tar.gz
Starting download
Connection 1 finished
Connection 2 finished
Connection 3 finished
Connection 0 finished …
```
> fix(error_log,install-local): ensure `$LOGDIR` exists before writing to it

- misc/scripts/install-local.sh
I run my system with a 0007 umask, which means some of the files and directories created by pacstall with sudo aren't then readable by it when it returns back to running as a normal user.
Simply chmod the files / directories after they are created. There doesn't seem a way to change the umask of sudo-invoked processes easily, looks like that would require modifying sudoers - that might be worth considering in future if it turns out there are many other places that need fixing up.
This patch fixes the two locations I've found so far, but I suspect there are others. It's good enough to allow me to install the package I wanted :)
> fix(install-local): ensure dirs made by sudo are readable

- misc/scripts/install-local.sh
When downloading patches, `wget -q` includes URL parameters in the resulting filename. This causes e.g. patches from the AUR to have `?h=${pkgname}` appended to their filenames, which is ugly.
The `-O` flag for `curl` tells it to use the remote file name, so it ignores URL parameters, solving the problem. Otherwise the functionality is identical.
One potential issue is that the `--output-dir` flag was introduced in `curl` 7.73.0, and the Debian 10 non-backports repo (and by extension, Ubuntu 20.04) uses an older version. An easy solution is to `cd` into PACSTALL_patchesdir, download the patches and `cd` back. But I'd like to discuss which approach is best.
> fix(install-local.sh): use `curl -sO` instead of `wget -q` for downloading patches

- misc/scripts/install-local.sh
`FARCH` only worked if the given pacscript's `arch` array was singular (i.e. if more than one foreign architecture was listed, then it did not work)
Fix the check to loop properly
> fix(install-local.sh): do more repair to `FARCH` array

- .github/workflows/publish-docker.yml
need both multi-arch (amd64+arm64) and multi-distro (ubuntu+debian) images. 
Example workflow:
https://github.com/oklopfer/pacstall/actions/runs/8008403762
(yes they are the same commit, but on different branches; shows that develop does not mark latest)
(with version tag)
naming scheme:
`ghcr.io/pacstall/{ubuntu,debian}-{distro_release}:{ref}`
refs are:
- `master`, `master-{hash_shortform}`
- `develop`, `master-{hash_shortform}`
- `version_tag` (like `4.3.2`)
- `latest` (either `master` or `version_tag`, never `develop`)
architecture is automatic to host device
> feat(CI): turn docker images into locally produced matrix

- install.sh
- misc/scripts/build-local.sh
- misc/scripts/download-local.sh
- misc/scripts/download.sh
- misc/scripts/install-local.sh
- misc/scripts/upgrade.sh
- pacstall
`pkgbase` usage is actually for multiple packages with the same source script, not for singular packages with multiple source entries in the same script. (see: https://archlinux.org/pacman/PKGBUILD.5.html#_package_splitting) This needs `package_foo()`/`build_foo()`/`prepare_foo()` syntax and a few other things, so it will be further down the line.
what I created as `pkgbase` should actually have been `srcdir`, but this means replacing `SRCDIR` with a new name.
`SRCDIR` -> `PACDIR`
`srcdir` -> `pacdir`
`pkgbase` -> `srcdir`
`pkgbase` to be reintroduced at a later point.
> chan(*)!: `SRCDIR` -> `PACDIR`, `pkgbase` -> `srcdir`

- misc/scripts/upgrade.sh
Pacstall isn't detecting updates on some packages that have variable checks, because it doesn't know about variables exported from `install-local.sh`. Then, even when it should know about them (`CARCH` and `DISTRO`), it drops them due to the series of subshells `upgrade.sh` puts the sourcing in. 
Pull it out of one less subshell and let the variables be exported from `upgrade.sh`, too.
See [1033](https://github.com/pacstall/pacstall/issues/1033) for more context, but we can observe:
```bash
[63:NOFUNC():1] - DEBUG: name=vscode-deb
[63:NOFUNC():2] - DEBUG: arch=("amd64" "arm64" "armhf")
[63:NOFUNC():3] - DEBUG: gives=code
[63:NOFUNC():4] - DEBUG: pkgver=1.85.0
[63:NOFUNC():5] - DEBUG: homepage=https://code.visualstudio.com/
[63:NOFUNC():6] - DEBUG: pkgdesc='lightweight but powerful source …
```
> fix(upgrade.sh): export `CARCH` & `DISTRO`

- misc/scripts/build-local.sh
- misc/scripts/checks.sh
- misc/scripts/download-local.sh
- misc/scripts/install-local.sh
PKGBUILD parity
`url` -> `source_url`, except in `checks.sh`, make that one a distinct `test_source_url`
`homepage` -> `url`, but not for `query-info.sh` + metadata
> chan!(*): `url` -> `{test_,}source_url`, `homepage` -> `url`

- misc/scripts/checks.sh
- misc/scripts/download-local.sh
- misc/scripts/install-local.sh
PKGBUILD parity, see: https://wiki.archlinux.org/title/PKGBUILD#Integrity
turn hash into an internally appended array that takes `{b2 sha512 sha384 sha256 sha224 sha1 md5}sums=` or `*sums_${CARCH}=`
checksum methods are mutually exclusive for pacscripts
> chan!(*): `hash` -> `*sums`

- misc/scripts/build-local.sh
- misc/scripts/checks.sh
- misc/scripts/install-local.sh
https://wiki.archlinux.org/title/PKGBUILD#conflicts
https://www.debian.org/doc/debian-policy/ch-relationships.html#packages-which-break-other-packages-breaks
https://www.debian.org/doc/debian-policy/ch-relationships.html#conflicting-binary-packages-conflicts
right now, pacstall has only `breaks`, PKGBUILD has only `conflicts`, but `debian` has both.
just duplicate `breaks` array with `conflicts`, except also we weren't `deblog`-ing `breaks` before so we will now
also fix `Replace` -> `Replaces` logging, see: https://www.debian.org/doc/debian-policy/ch-relationships.html#overwriting-files-and-replacing-packages-replaces
it is confusing, not sure if conflicts + replaces should actually be separated completely, but imo it should stay as is for now. Breaks+Replaces situations seem like they …
> feat({build,install}-local.sh): add `conflicts` array

- misc/scripts/build-local.sh
- misc/scripts/download-local.sh
say it with me now:  PKG👏BUILD👏parity👏 
https://wiki.archlinux.org/title/PKGBUILD#install
if a package is already installed, PKGBUILDs can run `{pre,post}_upgrade` instead of  `{pre,post}_install`
also `pre_remove`, debian has prerm https://manpages.debian.org/testing/dpkg-dev/deb-prerm.5.en.html
if package is installed + an _upgrade option exists, use that for deb's `preinst/postinst` options instead of _install.
If a package is installed but an _upgrade option does not exist, fall back to the _install options.
Added pre_remove/prerm to the list
works, test with:
```bash
pkgname="test-pacscript-bin"
source="https://github.com/oklopfer/debs/raw/master/empty.tar.xz"
pkgver="0.0.1"
pkgdesc="test"
maintainer="Oren Klopfer <oren@taumoda.com>"
pre_install() {
echo "this is pre-install"
} …
```
> feat({build,download}-local.sh: add `{pre,post}_upgrade`, `pre_remove`

- misc/scripts/build-local.sh
it should have been unset, causes problems when running with multiple pacscript installs at the same time if not unset.
unset it
> fix(build-local.sh): unset `compatible`

- misc/scripts/build-local.sh
- misc/scripts/download-local.sh
- misc/scripts/install-local.sh
if we are doing so many breaking changes, it is better to make our formatting future proof. also, PKGBUILD parity.
we entered the first source entry to maintain pacscript compat. but that causes problems, because all subsequent entries are placed here, meaning if a user cp'd the whole directory, it would have carried too much.
- introduce the PKGBUILD `_archive` variable; users can set it for usage in their script, or it will fall back to the first source entry's extracted directory
- change `srcdir` to always be `/tmp/pacstall/$pkgname~$pkgver` or `/tmp/pacstall-pacdep` if PACSTALL_PAYLOAD
- cd back to `srcdir` for everyone after down/extr, regardless of if we cd'd
- all current pacscripts should start with `cd $_archive` in prepare, build, and package
- pacscripts which used `cd ..` …
> chan!(download-local.sh): break out `srcdir` -> `srcdir` + `_archive`

- misc/scripts/build-local.sh
- misc/scripts/download-local.sh
- misc/scripts/install-local.sh
- misc/scripts/query-info.sh
if a `-deb` script defined a pacdep, or a dependency that the deb did not think it needs, it wasn't actually marked as a dependency by dpkg. 
Also, downloading a deb with -B needed verbosity.
Unpack the deb in a temp location, parse the control file for the Depends line, create an array, insert pacdeps, depends, and makedepends into the array, print it back out into the control file, repack the deb, install it.
also give downloading them with -B verbosity
> fix(*-local.sh)!: mark `pacdeps` as deps for `-deb` pacs

- install.sh
Downloading a potentially large amount of data quietly makes the install look like it hangs. There's no good reason to hide this information from the user. The warning about the CLI interface may be annoying, but it's much less of a UX issue than downloading hundreds of megabytes without any clear indication of doing so.
The very first invocation is more debatable to me, since it's more of a check than anything else. However, I also question the need to install both `curl` and `wget` during the installation - one of them is entirely sufficient.
> chan(install.sh): remove `-qq` from most `apt` invocations

- misc/scripts/download-local.sh
pacstall hooks are different from debian hooks when in the case of `-deb`s. 
distinguish them with verbosity. Also fix missing post_upgrade hook. Also make final cleanup terminology equal for `-debs` to how it was for everyone else (using `fancy_message sub` and announcing package finished installing)
> fix(download-local.sh): be verbose about pacstall hooks for -debs

- misc/scripts/build-local.sh
- misc/scripts/bwrap.sh
- misc/scripts/install-local.sh
was too lazy to figure this out yesterday ig
this prevents sudo from being useable in `{prepare,build,check,package}`
~~alias sudo inside bwrap functions, then we can block net successfully~~ none of these solutions worked what the frick
- `pkgver()` (or what replaces it) has new restrictions, and we have switched to using it internally. For the output `.deb`, if the package is a `-git`, then the trailing `git_pkgver` will automatically be calculated during cloning (separate from the defined `pkgver` variable); this includes based on any `#branch=`,`#commit=`, or `#tag=` if provided in the source entry. 
- This calculated output is accessible via `${git_pkgver}` to a pacscript, and can be overwritten for the _functions_ in a pacscript (i.e. setting `git_pkgver=` and then using it in for …
> fix(bwrap.sh): drop net

- misc/scripts/dep-tree.sh
if a package is both has pacdeps and is itself a pacdep, it should be called lower than packages that have pacdeps and themselves are not already pacdeps
expand the groups to the following priority, in descending order (1 is highest priority):
```
1)  pacdeps  +  !is_pacdep  +  !depends
pacdeps  +  !is_pacdep  +   depends
-----------------------------------------
2) !pacdeps  +  !is_pacdep  +  !depends
-----------------------------------------
3) !pacdeps  +  !is_pacdep  +   depends
-----------------------------------------
4)  pacdeps  +   is_pacdep  +  !depends
pacdeps  +   is_pacdep  +   depends
-----------------------------------------
5) !pacdeps  +   is_pacdep  +  !depends
-----------------------------------------
6) !pacdeps  +   is_pacdep  +   depends
```
> fix(dep-tree.sh): expand classes

- misc/scripts/download-local.sh
- misc/scripts/search.sh
- misc/scripts/upgrade.sh
when a package's `_remoterepo` is no longer existent in the `pacstallrepo` file during `-Up`, we are currently removing the repo link from the metadata of the package. This is bad practice, as in the case of simply switching to an updated repo (like `5.0.0-master`), packages are wiped from being updatable until re-installing.
- Fix up ancient code regarding `REPOS` + `remoterepo` that was written by someone who was not paying any attention to what they were doing. 
- When a repo mismatch happens, now rather than removing their remoterepo entirely, we are replacing it with the string `_remoterepo="orphan"`, which gives the packages special treatment separate from a `local` install, where they can still be found by `-Up`.
- Also, if a repo was commented out in the `pacstallrepo` file, it …
> fix(upgrade.sh)!: repair old REPOS code

- misc/scripts/build-local.sh
- misc/scripts/bwrap.sh
- misc/scripts/checks.sh
- misc/scripts/download-local.sh
- misc/scripts/install-local.sh
- pacstall
also fixes makedepends logging with constraints
if, and only if, both the `checkdepends` array and the `checks` function are present in the pacscript, then the array will also be considered with installing build depends (though they remain separate when providing output for distinction)
> feat(*): add `checkdepends` array

- misc/scripts/bwrap.sh
- misc/scripts/checks.sh
- misc/scripts/download-local.sh
- misc/scripts/install-local.sh
PKGBUILDs provide `_architecture` extensions for all these arrays, so we should too
make a new function that can loop through them dynamically, and append them to the main array
here's everything that gets the treatment:
- `source` (already had)
- `*sums` (already had)
- `depends`
- `makedepends`
- `optdepends`
- `pacdeps`
- `checkdepends`
- `provides`
- `conflicts`
- `breaks`
- `replaces`
- `gives` is also added, but is treated as a single string instead of an array; so if `gives` is absent but `gives_CARCH` is present, then `gives` becomes that.
These are the architectures we support (the current "officially supported" [Debian ports](https://www.debian.org/ports/)):
- `amd64`
- `arm64`
- `armel`
- `armhf`
- `i386`
- `mips64el`
- `ppc64el`
- `riscv64`
- `s390x`
> feat(*): add many more `var_CARCH` style arrays

- misc/scripts/download-local.sh
- misc/scripts/install-local.sh
- pacstall
it doesnt work rn with 5.0.0
let `PACSTALL_PAYLOAD` still be a string, that can pass `;:` (semicolon first) as a delimiter, which pacstall can then split into an array.
utilize our new `file://` download function that copies local stuff, and inject it into payload array urls
> fix(*): adjust `PACSTALL_PAYLOAD` to be array compatible

- misc/scripts/install-local.sh
- pacstall
At the moment we disable prompts on pacdeps regardless of the `-P` flag. We should only disable when the flag is used, as this can be a security risk.
Check the `$DISABLE_PROMPTS` variable when setting the pacdep installation command.
> fix(install-local): reenable prompts on pacdeps when prompts are not disabled

- pacstall
We currently don't:
- deduplicate flags
- check if more than one command flag is being used
- properly parse `-h` in argument cluster
- reorder long flags options correctly
But we should.
Fix it all
It's done and tested
> fix(main): rework argument parsing and handling

- misc/scripts/build-local.sh
- misc/scripts/bwrap.sh
- misc/scripts/download-local.sh
- misc/scripts/install-local.sh
- misc/scripts/upgrade.sh
- pacstall
`-deb`s need to work good in 5.0.0
- `-deb`s now handle pkgrel
- `-deb`s now properly log installed size
- `-deb`s version checking fixed with -Up
- `-deb`s -Up early exit fixed
- `-deb`s bwrap typo fixed
> fix(*): `-deb` handling

- misc/scripts/build-local.sh
Pacstall metadata reports `install_size` in the same format of `dpkg` control files, which outputs it into unitless bytes, while `apt info` and `aptitude` are smart enough to convert to human readable format.
Report `install_size` with the same formatting and conversion as `apt` does.
Related to https://github.com/pacstall/pacstall/pull/1082
> fix(build-local.sh): report `install_size` like `apt info`

- misc/scripts/upgrade.sh
Fix insane stty behaviour on ubuntu 22.04  after `pacstall -Up` caused by multiprocess `wait`
Same approach as #577
It works on my machine
Related to #571
> fix(upgrade): insane stty 2: electric boogaloo

- misc/scripts/checks.sh
source_CARCH is appended to source prior to checks being run; when I made that check earlier in develop, this was not the case at the time
so now it’s getting doubled up
but it needs to check if both source and source_CARCH exist and contain debs, and fail out in that instance
if source length is <= 1, and if source_CARCH length <= 1, and if source == source_CARCH, dont append it to test_source
> fix(checks.sh): fix `source_CARCH` appending

- misc/scripts/bwrap.sh
We need to pass some extra vars to the bwrap-ed functions.
set vars inside bwrap
Done.
Fixes anything that uses `$NCPU`, among others
> fix(bwrap): missing vars when running functions

- misc/scripts/version-constraints.sh
eifuvi issue with `repacstall`
```bash
Reading package lists... Error!
[!] ERROR: Failed to install ulauncher-deb deb
dpkg: warning: ignoring request to remove ulauncher-deb which isn't installed
[+] INFO: Cleaning up
```
```
python3:any ( (>= 3.7~)) libgtk-3-0 ( (>= 3.22)) gir1.2-gtk-3.0 gir1.2-webkit2-4.1 | gir1.2-webkit2-4.0 gir1.2-glib-2.0 gir1.2-gdkpixbuf-2.0 python3-gi python3-gi-cairo gobject-introspection gir1.2-gtklayershell-0.1 python3-xlib gir1.2-xapp-1.0 xapps-common
Package: ulauncher
Version: 6.0.0~beta10
```
```bash
python3:any (>= 3.7~) libgtk-3-0 (>= 3.22) gir1.2-gtk-3.0 gir1.2-webkit2-4.1 | gir1.2-webkit2-4.0 gir1.2-glib-2.0 gir1.2-gdkpixbuf-2.0 python3-gi python3-gi-cairo gobject-introspection gir1.2-gtklayershell-0.1 python3-xlib gir1.2-xapp-1.0 xapps-common
Package: …
```
> fix(version-constraints.sh): drop parantheses in formatting

- pacstall
Fix and improve the broken lock function, since it breaks everytime you guys add a new option flag. Now all you need to do is increase a variable.
Make the lock interate over a sequence of numbers, and use indirect expasion to access the args. We currently have `5` option flags. We check if any of the args from `1` to `$option_flags+1` is an ignored command flag, or if any of the args from `2` to `$option_flags+2` is a pacdep, since those are all the possible positions.
Done and tested.
Why are there so many option flags?
> fix(main): improve flag-aware lock

- misc/scripts/upgrade.sh
Fix insane stty behaviour on ubuntu 22.04  after `pacstall -Up` caused by multiprocess `wait`
Same approach as #577 and #1084
It works on my machine
Related to #571. Hopefully this is the last one.
> fix(upgrade): insane stty 3: return of the king

- misc/scripts/search.sh
because of 
for pacdeps, the `PACKAGE` variable is already available, so just check if the pacdeps file exists for it, and keep the variable as that instead of overwriting with `$i`, which is pulled from the upgrade loop for parents.
> fix(search.sh): repair `pacdeps` updating

- misc/scripts/bwrap.sh
Since we tmpfs `/run` with bwrap, dns resolution is borked. So we just need to ro-bind the `/run/systemd/resolve` dir.
Add the flag to bwrap
Done and tested with cargo packages
> fix(bwrap): dns resolution in the sandbox

- misc/scripts/build.sh
- misc/scripts/package.sh
if I install a pacdep manually, it loses connection to its parent, and is not properly logged as a pacstall depends in metadata.
in build.sh, check if existing metadata lists this package as a pacdep; if so, log it as one. 
in package.sh, if the package is already installed, check if it has the declaration in its metadata; if not, add it
part of https://github.com/pacstall/pacstall-programs/pull/5986
> fix({build,package}.sh): log previously installed pacdeps as such

- misc/scripts/version-constraints.sh
I goofed, the check was always returning positive
fix it
```bash
rhino@docker-desktop:~$ str="libc6>=2.38" && [[ ${str} =~ \(.+\) ]] && echo yes
rhino@docker-desktop:~$ str="libc6 (>= 2.38)" && [[ ${str} =~ \(.+\) ]] && echo yes
yes
```
> fix(version-constraints.sh): correct parentheses check

- misc/scripts/upgrade.sh
> fix(upgrade.sh): ensure `PACDIR` exists before creating tmps

- misc/scripts/bwrap.sh
- misc/scripts/package.sh
- misc/scripts/quality-assurance.sh
- pacstall
some environments, namely chroot style ones, are purely incompatible with bwrap. one such vital example is rhino linux's ISO builder/debian live-build, which uses chroot.
add a flag to allow builds in these environments to skip using bwrap, instead just running as sudo. While this is of course how pacstall worked before 5.0.0, we acknowledge that it is dangerous, and provide a strict warning when the flag is used
> feat(bwrap.sh): `--nosandbox`/`-Ns` flag

- misc/scripts/add-repo.sh
- pacstall
we should allow this tbh
just look below
- `github:user/repo` (defaults to branch `master`) [also works with provider `gitlab`]
- `github:user/repo#branch` [also works with provider `gitlab`]
- `local:/path/to/dir`
- ~~**add alias options to call repos**~~ save for 5.2.0
> feat(add-repo.sh): allow `-Rr`/`--remove-repo`

- misc/scripts/bwrap.sh
- misc/scripts/checks.sh
- misc/scripts/fetch-sources.sh
- misc/scripts/package.sh
- misc/scripts/upgrade.sh
- pacstall
bc I want it and also cross compatibility with PKGBUILDs
- export `AARCH` variable for script usage
- if `arch` array contains `AARCH`, use that for appending + checks instead of `CARCH`
- also singularize both known sums + known arch declares
- don't allow mixing and matching, must choose one style
> feat(*): allow arch-style architecture naming

- misc/scripts/checks.sh
- misc/scripts/fetch-sources.sh
to avoid having to declare a million distro arrays
don't append enhanced source for deb pkgs, override them
this means the arrays will work functionally different to normal `source`, and should be treated with care
for the example here: 
https://github.com/pacstall/pacstall-programs/blob/a55708b38c384737909462ce54cb0eca669a2fbf/packages/virtualbox-deb/virtualbox-deb.pacscript#L11C1-L12C85
instead of 
```bash
source_bookworm=("https://download.virtualbox.org/virtualbox/${pkgver}/virtualbox-7.0_${pkgver}-${release}~Debian~bookworm_amd64.deb")
sha256sums_bookworm="a8a65f3b77ace18abf48440859ba0fcfe33cba02d745ab7f12eb19fc18338298"
source_ubuntu=("https://download.virtualbox.org/virtualbox/${pkgver}/virtualbox-7.0_${pkgver}-${release}~Ubuntu~jammy_amd64.deb") …
```
> fix({fetch-sources,checks}.sh): override with enhanced source for `-deb` pkgs

- misc/scripts/build.sh
standardize to normal debian package naming scheme
just do it
> fix(build.sh): name `.deb`s correctly

- misc/scripts/fetch-sources.sh
they are quiet by default, which is wrong
use the power of eval and [@]
> fix(fetch-sources.sh): make git clones follow quiet rules

- misc/scripts/build.sh
- misc/scripts/checks.sh
- misc/scripts/fetch-sources.sh
- misc/scripts/package.sh
- pacstall
pull in more debian control fields
adds the following:
- `enhances` (+ enhanced arrays)
- `recommends`  (+ enh arrs)
- `makeconflicts` (+ enh arrs)
- `checkconflicts` (+ enh arrs)
- `custom_fields` (NO enhanced arrays)
- has a check to ensure field is not already used by pacstall, and is valid to debian format
- no space
- no numbers
- first uppercase, rest lowercase
- hyphen not trailing
- hyphenation follows same case rules
- array formatted such as:
```bash
custom_fields=(
"Example-Field: this, that, those"
"Exampler: This one is a long description
that goes on multiple lines"
)
```
- breaks `conflicts` off of `replaces` ~~(run tests to ensure this is okay, might need to include `conflicts=("${replaces[@]}")` in packages)~~ can confirm this is all good
> feat(*): provide more `control` fields

- misc/scripts/fetch-sources.sh
- misc/scripts/package.sh
unneeded builddeps can be marked for auto removal 
build a dummy
> fix({fetch-sources,package}.sh): install builddeps as a dummy

- misc/scripts/package.sh
Because `replaces` should be used in conjunction with either `breaks` or `conflicts`, this check should be run first, otherwise the former two will prevent replacing.
Just move it to the top of the check we do
https://github.com/pacstall/pacstall-programs/pull/6099 should not be failing on its checks, but is because of this.
> fix(package.sh): run `replaces` check before `breaks`/`conflicts`

- misc/scripts/fetch-sources.sh
in order to build the package (`-B`), we have to install the build deps
in the builddep subshell, set `PACSTALL_INSTALL` to `1`, which in this case means `true`
> fix(fetch-sources.sh): make sure builddeps always install and not build

- install.sh
- misc/scripts/build.sh
- misc/scripts/bwrap.sh
- misc/scripts/fetch-sources.sh
- misc/scripts/package.sh
- misc/scripts/update.sh
- misc/scripts/upgrade.sh
for distros like pop, elementary, mint, etc, they do not get special enhanced arrays. also removing lsb-release dependency
allow them to use the parent distro for enhanced arrays and compatibility checks. This works in different ways for each piece:
the following distro examples are described with the combination `child:codename/num|parent:codename/num`:
```bash
debian:trixie/13|debian:sid/sid
elementary:next/8|ubuntu:noble/24.04
linuxmint:elsie/5|debian:bullseye/11
linuxmint:virginia/21.3|ubuntu:jammy/22.04
pop:focal/20.04|ubuntu:focal/20.04
ubuntu:devel/2024.1
ubuntu:oracular/24.10
```
running `set_distro` results in:
```bash
debian:trixie
elementary:next
linuxmint:elsie
linuxmint:virginia
pop:focal
ubuntu:devel
ubuntu:oracular
```
and `set_distro parent` results in:
```bash
debian:sid …
```
> refactor(*): parse parent distro if exists

- misc/scripts/add-repo.sh
- misc/scripts/build.sh
- misc/scripts/bwrap.sh
- misc/scripts/checks.sh
- misc/scripts/dep-tree.sh
- misc/scripts/error-log.sh
- misc/scripts/fetch-sources.sh
- misc/scripts/get-pacscript.sh
- misc/scripts/package-base.sh
- misc/scripts/package.sh
- misc/scripts/quality-assurance.sh
- misc/scripts/query-info.sh
- misc/scripts/remove.sh
- misc/scripts/search.sh
- misc/scripts/srcinfo.sh
- misc/scripts/update.sh
- misc/scripts/upgrade.sh
- misc/scripts/version-constraints.sh
- pacstall
set -x is so hard to read sometimes
trap everything, trace it back
- All files and functions must have `{ ignore_stack=false; set -o pipefail; trap stacktrace ERR RETURN; }` at the top
- Any time `return 1` is provided by an internal function, it should be immediately preceded by `ignore_stack=true`, so that intentional error outs are not caught by the trace
- `stacktrace` will pipe back out the return codes it receives that are not `1`
in fixing this PR, three other changes/fixes happened:
1. if `depends` attributes have no aptitude match (like optdepends), then the script will fail out
- this also fixed optdepends from checking with apt-cache to checking with aptitude for arch enabled depends
- this also fixed all of the aptitude checks to properly check for architecture
2. `-git` …
> refactor(*): `stacktrace` and safe `rm`s

- install.sh
curl is currently broken on `sid` and not providing valid return codes, and we need it for our docker images.
drop `check_url` altogether. it will be very hard for someone to access this script without already having internet access anyway.
> fix(install.sh): drop `check_url`

- misc/scripts/build.sh
- misc/scripts/checks.sh
- pacstall
Adding another useful key that a control file can have.
If a script has the `bugs` variable defined, it will log that. If it does not, pacstall will figure out the URL to the repo's bug tracker based off of the repo where the script was downloaded from and log that instead. There is one case where `Bugs` will not be logged, and that is only if it is from a repo system that pacstall does not know about (listed in [Addendum](#Addendum)).
This variable will/should rarely be used manually, and 99% of the time should be left as-is, but for those who want more control over the processed deb, it is available now.
I have also pulled the system already in place that determines repo URLs and moved that into `/bin/pacstall`. Currently the available repository systems are supported for parsing:
1. …
> feat: add `bugs` variable

- misc/scripts/fetch-sources.sh
- misc/scripts/package.sh
- pacstall
whoopsie
- don't accidentally over clean up on `-deb` installs (it runs after install complete)
- don't throw pacdeps info message more than once
- redundant check
https://github.com/pacstall/pacstall-programs/pull/6199
> fix(*): cleanup again

- misc/scripts/build.sh
fixes virtualness for pacstall built packages that exist in apt repos
> fix(build.sh): always log at least one `provides`

- misc/scripts/package-base.sh
- pacstall
we can call them like this from parent repo as described in release, so we should be able to do it on local ones too
`/path/to/package.pacscript:${child}`
`/path/to/package.pacscript:pkgbase`
fail out if not exist
> fix(package-base.sh): accept child calls for local pacscripts

- misc/scripts/srcinfo.sh
elsie does cooler stuff at a lower level for mapping the enhanced arrays and it was not being passed all the way up correctly
fix the matching
> fix(srcinfo.sh): allow read for enhanced arrays

- misc/scripts/build.sh
if building split packages, pacstall waits to run cleanup until the end of the script, but some cleanups are based on `pacname`
clean them up inside of the function they're being used in at the end (doesn't work inside of earlier loops because of `wait` shenanigans)
> fix(build.sh): cleanup dep files immediately

- misc/scripts/build.sh
- misc/scripts/checks.sh
- misc/scripts/fetch-sources.sh
- misc/scripts/package-base.sh
- misc/scripts/package.sh
- misc/scripts/srcinfo.sh
- pacstall
because of how optdeps works, sometimes when building static packages one needs to just use the suggests array.
refactor `prompt_optdepends`
> feat(*): add regular `suggests` array

- misc/scripts/build.sh
they can and sometimes need to handle relations (particularly `provides`)
now we have `deblog_depends` which auto formats constraints arrays for deblog so use it for all relations
https://github.com/pacstall/pacstall-programs/pull/6273
> fix(build.sh): log all relations with dep const

- misc/scripts/build.sh
- misc/scripts/package.sh
we should do the removal right before installation of the new package, rather than earlier on
also, we should be checking replaces/conflicts/breaks before installing pacdeps, not after
reorder
> fix({package,build}.sh): re-order replaces removal

- misc/scripts/search.sh
- pacstall
integrating srclist
* add 2 new thingies
* `-Si/--search-info` command, searches remote srclist for SRCINFO data
* `-Sd/--search-description` command, searches both display descriptions and query including descriptions (keyword)
* `-Qi/--query-info` renamed to `-Ci/--cache-info` for clarity between `-Si`, functionally identical
* fix some inconsistencies when searching by repo (did not take into account masks + did not treat search results as an array)
* regular search now sorts packages from multiple repos alphabetically (i.e. mixed together) rather than separate by repo
> feat(search.sh): keyword and info search

- misc/scripts/package.sh
when repo search on pacdeps did not have a `$REPO` (aka local install), it was stacktracing & cleaning up secretly, but we could not see it
only do the search if `$REPO` exists
Fixes issue found in https://github.com/pacstall/pacstall/pull/1209
> fix(package.sh): repair bad cleanup on local pacscripts

- misc/scripts/checks.sh
- misc/scripts/fetch-sources.sh
when I wrote these originally I did not know enough about namerefs, and as a result I wrote bad and eventually buggy code
treat them correctly as arrays now
Fixing bug found in https://github.com/pacstall/pacstall-programs/pull/6270
```bash
pkgname="pacstall-qa-git"
source=("git+https://github.com/pacstall/pacstall-qa")
pkgver="0.0.1"
gives="pacstall-qa"
makedepends=("make")
pacdeps=("nushell-bin")
pacdeps_debian=("rhino-pkg-git" "rhino-neofetch-git")
pkgdesc="A tool to easily test pacscripts from PRs locally"
maintainer=("Oren Klopfer <oren@taumoda.com>")
build() {
cd "${_archive}"
mkdir -p "${pkgdir}/usr/bin"
mkdir -p "${pkgdir}/usr/share/pacstall-qa"
}
package() {
cd "${_archive}"
DESTDIR="${pkgdir}" make install
}
```
before:
after:
> fix({fetch-sources,checks}.sh): cleanup namerefs

- misc/scripts/fetch-sources.sh
They use stupid naming practices
Fix them up
Closes #1215
> fix(fetch-sources.sh): handle `devuan` and `kali` properly

- misc/scripts/build.sh
- misc/scripts/fetch-sources.sh
- misc/scripts/version-constraints.sh
if a package has both version constraints and is only available as `all`, it needs that as its architecture upon search
do that check and also clean up the other aptitude checks
https://github.com/pacstall/pacstall-programs/pull/6368
> fix({build,fetch-sources,version-constraints}.sh): `all` checks

- misc/completion/bash
I goofed on #1189 at the part about getting the urls from `pacstallrepo`. ZSH should no longer scream mapfile errors.
> fix(bash): add zsh exception for mapfile

- misc/scripts/fetch-sources.sh
- misc/scripts/package-base.sh
- misc/scripts/package.sh
- pacstall
When building split packages, the `prepare` and `build` functions should only be run once, and the download of `source` entries should only be performed once. Pacstall currently does not abide by this, causing: https://github.com/pacstall/pacstall-programs/pull/6339#issue-2469229994
- Switch `srcdir` from being based off of `pacname` to `pkgbase`
- If `pacname` is not the first entry in the `pacnames` list, `touch` the file `/tmp/pacstall-no-download-${pkgbase}`
- If this file is present:
- Do not run the download functions (as they were already run)
- Do not run `prepare` or `build` (as they were already run), only `check` and `package_${pkgname}`
- Make sure this file is cleaned up both at the end of the package split loop, and in `cleanup` as backup
<details>
<summary>log showing that …
> fix(*)!: `pkgbase` download and function overkill

- misc/scripts/fetch-sources.sh
- misc/scripts/package.sh
Allows us to git rid of/work around `_archive` by explicitly defining the name of the extracted folder
NOTE: `_archive` will be removed entirely in a separate PR
- Where before we allowed:
- `custom-location.zip::git+file://example.com/archive.tar.xz?h=file#branch=master`
- We now allow (in addition):
- `custom-location.zip@extracted_location::git+file://example.com/archive.tar.xz?h=file#branch=master`
- `@extracted_location::git+file://example.com/archive.tar.xz?h=file#branch=master`
Where one can then use `cd extracted_location` instead of `cd ${_archive}` (the variable is internally called `${to_location}`, per source)
For `.git` and non-extractable sources, `${dest}` already performed this function, so `${to_location}` is ignored.
> feat({fetch-sources,package}.sh): allow extract-to syntax for `source`

- misc/scripts/search.sh
not supposed to be there and makes the error print wrong (we can see on the debian CIs failing rn)
remove
> fix(search.sh): rm weird stray printf thing

- misc/scripts/build.sh
if I have the optdeps preinstalled, and i go to build the package, it will mark already installed optdeps as deps, counter to how it should work, where in build mode they are supposed to be all auto marked as suggests
if pacstall_install is 0 dont mark anything off as already installed
> fix(build.sh): don't mark already installed optdeps as deps in build only mode

- pacstall
It looks a lot nicer and is more immediately recognized as a separator.
Should be merged after #1274 because it touches the same areas.
> fix(suggested_solution): use double dash as separator instead of "ZZZZ"

- misc/scripts/package.sh
awk slow, bash fast.
Replace superfluous instances of awk with pure bash.
> perf: remove some awk instances in favor of variable substitution

- misc/scripts/fetch-sources.sh
elsie found an issue
if the resulting extraction is greater than 1 head file, to_location must be created for everything to be placed into
fixes 1password on programs#6702 (wont link so this doesnt accidentally close it)
> fix(fetch-sources.sh): extract-to oopsies

- misc/scripts/build.sh
if we run apt remove in most normal contexts, it will also remove all the packages depending on it.
If conflicts and breaks array dont contain an item in replaces, add it to conflicts, and let apt do the removing. Essential packages dont work with this (rhino-core stuff), so we still need to have the logic for them.
> fix(build.sh): repair replaces removal logic

- misc/scripts/bwrap.sh
last PR fixed the pacname issue but I realized that pkgbase can be empty if it is a singular package so for functions to access the value it needs to fallback pacname
> fix(bwrap.sh): fallback `pkgbase`

- misc/scripts/fetch-sources.sh
- misc/scripts/package-base.sh
- misc/scripts/search.sh
- misc/scripts/srcinfo.sh
- misc/scripts/upgrade.sh
- pacstall
A lot of our code didn't do anything, and was just gobbling up CPU time.
- Remove redundant rewriting of pkgbase parent variables
- Decouple `srcinfo.parse` from `srcinfo.match_pkg`
- `srcinfo.parse` now requires a second var to create an access file to write to
- Refactor `srcinfo.match_pkg` to map results to a ref instead of printing out in a subshell, and read from the access file
- Eliminate functions that did nothing:
- `srcinfo._promote_to_variable`
- `srcinfo.reformat_assoc_arr`
- `srcinfo.print_var`
- Fix description search only giving pkgbase parent + last result for split packages:
- Before: `foobar` parent exists with children `a` `b` `c`; description search responds: `foobar:pkgbase` `foobar:c`
- Now: description search responds: `foobar:pkgbase` `foobar:a` `foobar:b` …
> fix(*): make srcinfo parsing not resource heavy

- .github/workflows/publish-docker.yml
pros: will run docker builds wayyyyyy faster
cons: have to explicitly define each matrix combo now
> ci: use arm64 runners for docker

- misc/scripts/package-base.sh
- misc/scripts/srcinfo.sh
split packages should be able to access and use the extended array versions of their overrides
- fix override to allow extensions
- fix srcinfo to print extensions in children like parents
- speed up processing
> fix({package-base,srcinfo}.sh): give split pkgs access to extended arrays

- misc/scripts/search.sh
The `URLLIST` array wasn't getting properly updated when a package is masked.
This is a very rare edge-case, only affecting a couple of packages on multi-repo setups of rhino linux, usually the first of each repo.
Unset the index of `URLLIST` along side `PACKAGELIST`.
Done and tested.
I don't like our package masking. I feel like it has always been a bad idea and that there are better ways to get the same result.
> fix(search): fix origin url index of packages when masking packages

- misc/scripts/fetch-sources.sh
- misc/scripts/package.sh
if a source has no compression method clearly defined in the URL, pacstall won't try to extract it, and doesn't currently allow dest to ever control extraction method to override that behavior
if no compression method is found from `source_url`, then nest down to `dest` to perform the same check, but without `file://`, `.git`/`git+`, or `.deb`; fallback to the old way if `dest` also has no compression method defined
> fix({fetch-sources,package}.sh): allow `dest` to define extr when `source` doesn't

- misc/scripts/srcinfo.sh
- misc/scripts/upgrade.sh
- pacstall
fix vars that are acting weird:
- fixes download of split package pacscripts
- fixes `_pkgbase` bleeding during upgrade
- fixes split packages reading `pkgbase` var
side note, srcinfo change does *not* need to be brought into programs or pacup
> fix({srcinfo,upgrade}.sh): repair split pkg upgrades

- pacstall
Some packages are too big for some device's tmpdirs
give an envar for users to override the `/tmp` part of `PACDIR` (so if someone tries `PACSTALL_TMPDIR=/` it won't nuke them)
https://github.com/pacstall/pacstall/issues/1324
> feat(pacstall): allow env to define TMPDIR

- misc/scripts/package.sh
Sometimes I'd like to see in the CI logs that pacstall is "succeeding" because of the `GITHUB_ACTION` variable.
> chan(package): exit 1 on CI incompat again

- README.md
Because now we have explicit disallowal of updates in debs, the reasoning behind the original warning is moot.
> chore(README): remove outdated warning to debs

- misc/po/pacstall.pot
- misc/scripts/build.sh
- misc/scripts/dep-tree.sh
- misc/scripts/query-info.sh
- misc/scripts/upgrade.sh
- pacstall
if a pacscript is local installed, it won't ever get checked for upgrades (problem if using double click mime install)
- treat locals like orphans
- add new `-M`/`--mark` command to set packages to be held from upgrading
> ref(*): allow local installs to be picked up by upgrade

- misc/po/pacstall.pot
- misc/scripts/bwrap.sh
- misc/scripts/package-base.sh
- misc/scripts/update.sh
- misc/scripts/upgrade.sh
- pacstall
#1334 didn't do enough
make the TMPDIR override its own variable that falls back to /tmp, and use that in place of /tmp anywhere in da code
> fix(*): respect TMPDIR override

- misc/scripts/fetch-sources.sh
- For all packages besides `-deb` packages, installation is already **always** run with `--allow-downgrades`.
- If a pacscript adds dependencies to a `-deb` package, it is rebuilt with `repacstall` and installed like all other packages, meaning it too is run with `--allow-downgrades`.
- Clean/unaltered `-deb` packages are the outliers here, who don't allow downgrades to occur. This has shown itself to be a problem before in the case of `nala-deb`, where what `dpkg` treats as a downgrade is not actually one, and is occurring for me when testing out adding [`firefox-deb`](https://github.com/pacstall/pacstall-programs/pull/7142), as it is trying to replace `firefox-bin` which uses Pacstall's semantic `-pacstall` versioning, while the deb itself does not. 
Give everyone the same behavior
> fix(fetch-sources.sh): allow `-deb`s to downgrade

- misc/po/pacstall.pot
- misc/scripts/bwrap.sh
- misc/scripts/checks.sh
- misc/scripts/fetch-sources.sh
- misc/scripts/package-base.sh
- misc/scripts/package.sh
- misc/scripts/upgrade.sh
- pacstall
Allow pacscripts to easily access running kernel version and apply kernel version constraints
- `KVER` internal variable available for usage in Pacscripts, equal to `uname -r`
- `limit_kver` pacscript variable that can be used like a version constraint (e.g. `limit_kver=">=4.4"`), which does a dpkg version comparison with `KVER`
~~- [x] consider if it should be added to SRCINFO~~ decided against for now, can always add later. If added, needs to be in:
- pacup srcinfo
- pacstall srcinfo
- programs srcinfo
- go srcinfo
- website API
- swagger docs
> feat: `KVER` and `limit_kver`

- misc/scripts/build.sh
- misc/scripts/version-constraints.sh
- pacstall
Installed packages incorrectly avoid detection of their version; in situations where `foo=1.0` is installed but `foo>=1.1` is specified, we are treating this as a valid match, because `foo` is installed.  For a cascade of reasons, this results in problematic situations like the following:
- Make `is_apt_package_installed` aware of version constraints, and return error (not installed) if constraints are not satisfied.
- Pass full package name + version strings in places where it is needed to `is_apt_package_installed`
`vala-panel-appmenu-xfce4-git` requires `valac-0.56-vapi` -> `valac-0.56-vapi>=0.56.18` in its `makedepends`, but this will currently cause breakage if the package is not updated to that version beforehand. Pacstall should be able to call this update.
> fix(is_apt_package_installed): check against version constraints

- misc/man/pacstall.5
- misc/man/pacstall.8
- pacstall
- bump `vala-panel-appmenu-xfce4-git` makedep of `valac-0.56-vapi` to `>=0.56.18` after release
> upd(pacstall): `6.2.1` -> `6.3.0`

- misc/scripts/fetch-sources.sh
I missed one in #1359 ....
pacstall 6.3.1 chartreuse baby!!!!
lets https://github.com/pacstall/pacstall-programs/pull/7420 actually work
> fix(fetch-sources.sh): use proper `is_apt_package_installed` check

- misc/scripts/checks.sh
- misc/scripts/package.sh
some checks need to be ran at different times than the rest
- move `checks` back to where it was pre-https://github.com/pacstall/pacstall/commit/c9e3cfa59a341e34e6a356a3aebb409b2891abee
- move the 5 that need to be run before the rest (`lint_pacname`, `lint_incompatible`, `lint_arch`, `lint_mask`, `lint_kver`) to `pre_checks`, which goes where `checks` was moved to in that PR
- ensure deb download only comes after `lint_source`
https://github.com/pacstall/pacstall-programs/pull/7587
> fix({checks,package}.sh): split up `checks` function

- misc/scripts/fetch-sources.sh
- misc/scripts/upgrade.sh
when orphans and using REPO, can cause bad like: `https://gitlab.com/pacstall/pacstall-programs/-/raw/master/-/raw/`
check if its already been formatted
wow 6.3.4
> fix({upgrade,fetch-sources}.sh): don't overwrite remotes already formatted
