pacstall/pacstall

.github/workflows/remote-bash.yml
README.md

Revert "Merge `master` into `develop`"

---

.github/workflows/remote-bash.yml
README.md

Revert "Revert "Merge `master` into `develop`""

---

misc/completion/bash
misc/scripts/install-local.sh
misc/scripts/upgrade.sh
pacstall

CodeFactor has graded this repository a C+. This PR aims to improve the Code Quality grading.
Fixing Code Quality issues brings performance benefits, better maintainability and cleaner code base

Fix Code Quality issues

---

misc/completion/bash
pacstall

Revert "Feature/bugfix"

---

pacstall

Pacstall can update both user and branch
`sudo pacstall -U wizard-28 develop` for example and if no input is specified, it will default to `pacstall` and `master`

Branch update with -U

---

pacstall

Add USERNAME instead of USER and fix quotes

---

pacstall

This PR fixes bugs in the update code block in `pacstall` file

Fix bugs in the update code block

---

.github/workflows/labeler.yml

This adds configuration to the auto-labeler for all label types.

 [enhancement] Configure the Auto-Labeler, test drive 2

---

.github/workflows/labeler.yml

This adds filters to the labeler
-----------------
If this works corrently then it should ignore tags lile
help, hotfix, bug
in the description and only look for tags in the title

[feature] Add filters to the labeler

---

.github/workflows/remote-bash.yml

Removed as it was triggered unnecessarily.
-------
Opened again with proper title

[bug] Remove CI testing on `push`

---

.github/workflows/labeler.yml

Changes name from `test` -> `labeler`

[bug] Change job name of `issue-action` github action

---

misc/scripts/install-local.sh

Some code was left behind when the suggestions was committed in https://github.com/pacstall/pacstall/pull/53
Also rewrote the if to a more readable version IMHO.

Removed obsolete code and some nitpicking

---

README.md

Nothing major, but since it's the first thing people will see, thought I might as well fix it

Fixed some weird grammar

---

README.md

I added the GPLv3 logo and the boilerplate to the `readme.md`, I think we also need a `COPYING.md` file...

License things

---

misc/scripts/install-local.sh

Remove line

---

pacstall

Add `-Il` flag to help menu

---

CONTRIBUTING.md
README.md
install.sh
misc/scripts/install-local.sh
misc/scripts/upgrade.sh

This PR aims to improve the Code Quality of the whole repo.

[enhancement] Improve Code quality

---

misc/scripts/install-local.sh

Fix: Execute `trapc` with sudo privileges

---

pacstall

Fix: Removed typo

---

misc/scripts/install-local.sh

Hey guys! I edited install-local script to support .deb packages, using wget and awk.
Related issues: #77

Feat: Added Alpha `.deb` support using `wget` and `awk`

---

misc/scripts/install-local.sh

Reverts pacstall/pacstall#93
It doesn't work

Revert "Feat: Added Alpha `.deb` support using `wget` and `awk`"

---

install.sh

Changed `PACSTALL_DIRECTORY` to `STGDIR`

Feat: cleanup installer

---

pacstall

Fix: pacstall will force stop running as root

---

misc/scripts/install-local.sh
misc/scripts/remove.sh

Where I fcked up earlier:
* Not sourcing LOGDIR
* Not copying pacscript
What I changed: fixed my nasty code. Changed my editor setting to expand tabs lmao and also source log before sourcing pacscript in remove.sh and copy pacscript in install-local.sh

Fix: Pacstall not removing `.deb` packages

---

misc/scripts/query-info.sh
misc/scripts/remove.sh
misc/scripts/update.sh

This PR aims to add the missing GPL boilerplate to the files.

Doc: Add missing GPL boilerplate

---

pacstall

Check if directory exists and if not, send an error message

Fix (main): fix #166

---

.github/workflows/remote-bash.yml

fix (workflow): rename brave package

---

pacstall

ref (main): bump version

---

misc/scripts/upgrade.sh

Fixes upgrade version comparison issue
`dpkg` is unable to compare version that don't start with a number.
Fix remote existence check, verify if package still has a remote pacscript and change version comparison.

Fix: `upgrade.sh` version check

---

misc/scripts/install-local.sh
misc/scripts/remove.sh
pacstall

Pacstall dummy packages currently cannot be removed with apt
Adds a postrm file that calls pacstall

Feat: Add postrm in dummy deb

---

misc/scripts/install-local.sh
misc/scripts/remove.sh
pacstall

Revert "Feat: Add postrm in dummy deb"

---

misc/scripts/install-local.sh
misc/scripts/remove.sh
pacstall

Pacstall dummy packages currently cannot be removed with apt
Adds a postrm file that calls pacstall

Feat: add postrm for apt integration

---

README.md

So people can more easily find the subreddit and the user repo

Add reddit and pacstall-programs links in readme

---

install.sh

The current `install.sh` isn't the greatest installation script. There are many Code Quality issues and bugs in it.
This PR is supposed to fix all those issues.
This is the initial revamp of the script, I guess more PRs will be made later with more revamps.

Feat: Initial `install.sh` revamp

---

CODE_OF_CONDUCT.org

Currently this repository has no official Code of Conduct. So problems may arise in the future.
This adds `The FOSS Code of Conduct` version `1.0` written by `Derek Taylor` ( aka `DistroTube` ), it was voted to be the CoC for this project many days ago in the Discord server.
The poll referenced is: https://discord.com/channels/839818021207801878/848159751161774100/867835315019186226

Feat: Add `The FOSS Code of Conduct`

---

misc/scripts/install-local.sh

We where sourcing the wrong file when making the postrm script for the dummy deb

Fix(scripts): fix wrong sourced file

---

uninstall.sh

In case someone doesn't want pacstall
Remove pacstall

Feat: Add removal script

---

misc/scripts/install-local.sh

Fix dependency install after installing dummy deb package

Fix: broken dependency install

---

misc/scripts/install-local.sh

"[It] looks better"
--_Wizard 28_

Add vertical spacing to makeDummyDeb

---

misc/scripts/install-local.sh

Revert "Fix: broken dependency install"

---

misc/scripts/install-local.sh

There where missing cleanups and the hashcheck didn't error out

Fix(scripts): add missing cleanups

---

misc/scripts/install-local.sh

It's a broken PR merged by mistake

Revert "dpkg ignore dependency "errors""

---

misc/scripts/install-local.sh

Currently we are asking the user to view, then to edit the pacscript. This can be done in a one step process instead of a two step one.
Remove viewing question. Directly ask to view/edit the pacscript

rem(install-local): View question

---

misc/scripts/download.sh

`wget`
`wget`
Make a checklist of your progress
`wget`

Fix: use wget for pacscripts

---

CONTRIBUTING.md

Currently the contributing guidelines doesn't have a linting clause. So people may try to submit lower quality code
Adds checking via `shellcheck` a requirement, so lower quality PRs may be eliminated.

feat(contributing): Add `shellcheck` requirement

---

uninstall.sh

The current uninstaller is riddled with bugs, and is a pain to use for the user.
This PR aims to remove the bugs, and make the uninstaller more user-friendly.

fix(uninstaller): Revamp

---

README.md

Currently in the README file there is no mention of the uninstall script. This is inconvenient for users.
Adds the uninstall section

feat(readme): Add uninstall section

---

misc/scripts/install-local.sh

Fixes https://github.com/pacstall/pacstall-programs/issues/221

feat(main): `chown` `STGDIR`

---

.github/CODEOWNERS
.github/pull_request_template.md

CODEOWNERS was not working as expected
Possibly fix CODEOWNERS by removing teams with members name

fix(github): `CODEOWNERS` and `PULL_REQUEST_TEMPLATE`

---

CODE_OF_CONDUCT.md

Markdown version of FOSS CODE OF CONDUCT
GH does not recognise current CoC
Translate FOSS CoC to MD

fix(CoC): Port it to markdown

---

misc/scripts/install-local.sh
misc/scripts/remove.sh
pacstall

this can help if a malicious pacscript attempts to change certain pacstall variables that could lead to unintentional consequences

Change certain variables to readonly

---

misc/scripts/install-local.sh
misc/scripts/remove.sh
pacstall

Revert "Change certain variables to readonly"

---

misc/scripts/install-local.sh

https://discord.com/channels/839818021207801878/866673569521991700/886661012143611915
unset `pkgver` after install

fix(install-local): Unset `pkgver` after install

---

README.md

Adding a link to the list of packages

---

misc/scripts/install-local.sh

Currently the `check` function doesn't do much, so I added more checks that look for vital variables and alert the user if there is an issue

feat(scripts): Add more checks to the check function

---

pacstall

Fixes #269 
Replace `return 1` with `exit 1`

fix(main): fixes #269

---

pacstall

Many code quality issues in the main file.
Fix them

fix(main): Code quality issues

---

misc/scripts/upgrade.sh

This fixes #273 which didn't create `SRCDIR`

fix(upgrade): Create `SRCDIR`

---

misc/scripts/add-repo.sh
misc/scripts/download.sh
misc/scripts/error_log.sh
misc/scripts/install-local.sh
misc/scripts/remove.sh
misc/scripts/search.sh
misc/scripts/update.sh
misc/scripts/upgrade.sh

The scripts have many code quality issues.
Fix them.

fix(scripts): Code quality issues

---

.github/workflows/workflow.sh

fix(workflow): Re-add `apt` installation to workflow

---

src/pacstall.py

Adds argument parser to `pacstall.py`
Using the `argparse` standard lib.

feat(pacstall): Add argument parser

---

misc/scripts/install-local.sh

fix(CI): Extract without root privileges 

---

src/pacstall.py

Add a locking mechanism to the main script, also move the argument parser to it's own function as a result.

feat(pacstall): Add locking mechanism

---

misc/completion/bash
misc/completion/fish
misc/scripts/install-local.sh
pacstall

This PR attempts to resolve issues laid out in https://github.com/pacstall/pacstall/commit/c08194f78e01297a11f71b4a4cd6028642a98f46#commitcomment-58773737
Moves old builds to `/tmp/pacstall-keep/$name` and add completions

feat(completions,install): Add missing `keep` features

---

README.md

The badges in the README are outdated.
Update those

feat(readme): Improve badges

---

pacstall

Fix lock function `$ignore` list
#388

fix(main): `$ignore` on lock function

---

misc/scripts/upgrade.sh

Properly add tabbing on the upgrade list
Closes #394

fix(upgrade): fix tabbing on upgrade list

---

misc/scripts/upgrade.sh

Fix typo that prints wrong type of fancy_message

fix(upgrade.sh): warning -> warn

---

misc/scripts/remove.sh

Fully remove package when using the `-R` flag.
Purge the package in order to remove metadata and the package completely.
Closes #434

fix(remove): incomplete removal of packages from apt's database 

---

.gitignore

Adds a generic python `.gitignore` file

chore: add `.gitignore`

---

pacstall/__main__.py
pacstall/api/error_codes.py

BREAKING CHANGE: The program can only be launched as root.
Closes #454

feat(main)!: only launch as root

---

README.md

Adds mastodon and reddit (updates it) badges.

docs(readme): add reddit and mastodon badges

---

install.sh
misc/scripts/update.sh
pacstall

Prevents possible breakage when running certain flags without an internet connection
Reuse the network checker from the installer

feat: add network checks

---

pacstall

bump: 1.7 -> 1.7.1

---

pacstall/__main__.py
pacstall/cmds/download.py
poetry.lock
pyproject.toml

Next step in https://github.com/pacstall/pacstall/issues/361, adds asynchronous downloads, progress bar, and properly downloads pacscripts instead of raw URLs.
Replace `requests` with `httpx`, and use `aiofiles` to achieve async downloads.
Use `rich`'s progress bars.

feat(download): rewrite

---

poetry.lock
pyproject.toml

build(poetry): remove unused dependencies

---

pacstall/__main__.py
pacstall/api/logger.py

Prevent certain flags from running without root, and offer a suggestion to run if it fails.
Check if the user is root.

fix: allow certain commands to run with root

---

pacstall/api/logger.py

The logger currently doesn't log to `stdout` at all, so it's hard to write tests for it, and limits parsing by other programs in the future.
Logs records lower than `WARNING` to `stdout` and higher to `stderr`.
Everything is still logged to the log file regardless.

fix(logger): log to appropriate streams

---

README.md

docs(readme): revamp

---

install.sh
misc/completion/bash
misc/completion/fish
misc/scripts/add-repo.sh
misc/scripts/download.sh
misc/scripts/error_log.sh
misc/scripts/install-local.sh
misc/scripts/query-info.sh
misc/scripts/remove.sh
misc/scripts/search.sh
misc/scripts/update.sh
misc/scripts/upgrade.sh
pacstall
uninstall.sh

Formats whole code base using `shfmt -bn -ci -sr -s`

style: reformat with `shfmt -bn -ci -sr -s`

---

misc/scripts/install-local.sh
pacstall

At many points in the code, there are inconsistencies about where to exit at, particularly how `-I` exits properly, but `-Il` fails to exit properly at the same point.
Fix them.

fix(pacstall): exit properly

---

pacstall

fix(pacstall): fix typo in `-V` flag

---

misc/scripts/update.sh

It doesn't make sense.
Remove it.

rm(update.sh): remove wacked apt command

---

pacstall

The current help message looks trashy and quickly made (it was).
Make it look decent.

feat(pacstall): spruce up help message

---

misc/scripts/update.sh

Fix insane stty behaviour on ubuntu 22.04 after `pacstall -U` caused by multiprocess `wait`
Closes #571

fix: remove insane stty bug on update

---

README.md

docs(readme): fix logo size

---

README.md

docs(readme): update link and change wording

---

.github/CODEOWNERS

chore(codeowners): add @NarutoXY back

---

misc/scripts/update.sh

The current `-U` output is hard to read and gives little information about the update. This PR will show the version and branch which are being updated to, as well as give a list of useful links, such as our website package list, GitHub page, Discord, and website
Add the stuff.

feat(update): display useful links and update status

---

misc/scripts/upgrade.sh

The current implementation doesn't show anything except for the packages being updated
Show version changes alongside the packages being upgraded.

feat(upgrade): show version changes

---

misc/scripts/install-local.sh

fix(install-local): add missing `ask` export

---

install.sh
uninstall.sh

Fixes faulty network checks in `install.sh`

fix(install): faulty network check

---

misc/scripts/install-local.sh

Pacdeps don't work in develop..
Fix control flow
fixes https://github.com/pacstall/pacstall-programs/pull/1357 and https://github.com/pacstall/pacstall-programs/pull/1348

fix(install-local): make pacdeps actually install

---

install.sh

Update `fancy_message` functions in `install.sh` and `uninstall.sh` to write error messages to `stderr`

fix((un)install): write error messages to `stderr`

---

misc/scripts/upgrade.sh

There are simpler and faster ways to accomplish the same goal.

refactor(upgrade): remove `awk`

---

misc/scripts/upgrade.sh

The upgrade is too slow, and this gets worse when there is more packages in the repos and packages installed
Multi-processing on the version fetch loop, reducing the bottleneck.

feat(upgrade.sh): Parallel package version comparison on upgrade

---

misc/scripts/install-local.sh
misc/scripts/query-info.sh

`pacdeps` does not have a relationship with the parent package right now.
Append `pacdeps` to the `depends` list that goes into the deb

fix(pacdeps): relationship to parent

---

README.md

fix(README): flat reddit logo

---

install.sh
misc/scripts/add-repo.sh
misc/scripts/download.sh
misc/scripts/error_log.sh
misc/scripts/install-local.sh
misc/scripts/query-info.sh
misc/scripts/remove.sh
misc/scripts/search.sh
misc/scripts/update.sh
misc/scripts/upgrade.sh
pacstall
uninstall.sh

Clean up the code.
Run `shfmt -w -i 4 -bn -ci -sr -kp -s <file>`

ref: run shfmt on every sh file

---

misc/scripts/install-local.sh
pacstall

fix: cat pacscript into post files

---

misc/scripts/install-local.sh

Current message can get really verbose.
Merge into one line.

style: merge not found in apt repos message

---

misc/scripts/install-local.sh

fix(install-local): fix more gives locations

---

misc/scripts/install-local.sh

Because some packages might need it.

feat(pacscript): add `provides` array

---

misc/scripts/install-local.sh
pacstall

feat: add links to useful pages to help flag

---

pacstall

ref: bashify update

---

misc/scripts/install-local.sh

fix(hashcheck): remove useless apt purge

---

misc/scripts/update.sh

fix(update): check for valid URL

---

pacstall

fix(help): add missing periods

---

pacstall

fix(check_url): redirect usage to /dev/null

---

pacstall

fix(-L,-Up): error out on arguments

---

misc/scripts/download.sh

fix(download): `suggest_solution` -> `suggested_solution`

---

.github/ISSUE_TEMPLATE/BUG-REPORT.yml

Why is it not also assigning me?
Fix it.

fix(BUG-REPORT): assign @Henryws

---

misc/scripts/add-repo.sh
misc/scripts/install-local.sh
misc/scripts/search.sh
misc/scripts/upgrade.sh

To make Pacstall faster. This particularly benefits `search.sh` as it now won't have to call on grep at every package.

perf: remove heavy external tools

---

misc/scripts/install-local.sh

fix(install-local): bring back interoperability between functions

---

install.sh

fix(install.sh): remove outdated tree dependency

---

misc/scripts/remove.sh

fix(remove): redirect source stderr

---

pacstall

chore(pacstall): Curtesy -> Courtesy

---

misc/scripts/install-local.sh

Currently we don't have a way of viewing large compilation logs in Pacstall.
Redirect stdout and stderr to a log file, and purge month old files.

feat: add logging to pacstall functions

---

README.md

Fixes https://github.com/badges/shields/issues/8671.

chore(README): fix badge route

---

misc/scripts/upgrade.sh

I forgot to add `epoch` checks into `upgrade.sh`.

fix(upgrade): take epoch into account

---

misc/scripts/install-local.sh

fix(clean_logdir): use exec

---

misc/scripts/remove.sh

We don't need to purge.
Remove instead of purging.

fix(remove): remove instead of purge

---

pacstall

rm(Il): remove deprecation notice

---

misc/scripts/install-local.sh

Evaling is needed in bash for this.

fix(homedir): eval it

---

misc/scripts/query-info.sh
pacstall

ref: use `dpkg-query` instead of `dpkg -s`

---

misc/scripts/error_log.sh
misc/scripts/install-local.sh

Some packages only work on certain archs.

feat(pacscript): add `arch` array (#793

---

misc/scripts/install-local.sh

hotfix(arch): use `all` instead of `any`, export CARCH always

---

pacstall

feat: add `NO_COLOR` support

---

misc/scripts/install-local.sh

Because I misread the stupid PKGBUILD wiki for the 2nd time..

fix(arch): recommend `any` instead of `all`

---

misc/scripts/install-local.sh

We clean the directory but not remove it.

fix(cleanup): remove `/tmp/pacstall` on cleanup

---

.pre-commit-config.yaml

style(pre-commit): use 4 space tabs

---

misc/scripts/upgrade.sh

It's fairly easy to inject random stuff into `/tmp/pacstall-up-{list,urls,print}`.
Use `mktemp` in order to generate a random tmp file.

fix(upgrade): use `mktemp` to prevent easy injection

---

misc/scripts/install-local.sh

Visually it looks nicer that the user can see the hashes side by side rather than just saying they are broken.

feat(hashcheck): show broken hashes

---

misc/scripts/install-local.sh
misc/scripts/upgrade.sh
pacstall

fix(SRCDIR): remove at end of everything, no recreation

---

misc/scripts/error_log.sh

fix(error_log): logs in `/var/log` should not be user writable

---

misc/scripts/install-local.sh

It's not really helpful and doesn't serve any purpose that I know of.

rm: useless `hash -r` run

---

misc/scripts/error_log.sh

fix(error_log): append instead of overwrite

---

misc/scripts/install-local.sh

Fixes error that @oklopfer found.

fix(pacdeps): remove with sudo

---

misc/scripts/install-local.sh
misc/scripts/update.sh
pacstall

feat(update.sh): allow local updates

---

misc/scripts/install-local.sh

Because stuff can be evaluated before `CARCH` is available.

fix(CARCH): set before source

---

misc/scripts/install-local.sh
misc/scripts/query-info.sh

It's useful for people who want to see the main site of the software they are downloading.
Closes #541.

feat(pacscript): add `homepage` property

---

misc/scripts/download.sh
pacstall

Because it's slow and we can just use bash for it.

perf: remove `basename` command

---

misc/scripts/install-local.sh
misc/scripts/update.sh
pacstall

We can remove grep *entirely* for internal bash stuff like regex.

perf(grep): remove grep cases for bash regex

---

misc/scripts/add-repo.sh
misc/scripts/install-local.sh
misc/scripts/search.sh
misc/scripts/upgrade.sh
pacstall
uninstall.sh

refactor(*): use `(())` instead of `[[ -eq ]]`

---

misc/completion/bash
misc/completion/fish

rm(completions): awk

---

misc/scripts/install-local.sh

feat(pacscript): change replace to array

---

misc/scripts/install-local.sh
pacstall

Remove build deps marked as removable..

fix(build_depends): prevent dep yoinking

---

install.sh
misc/scripts/update.sh
pacstall
uninstall.sh

perf(colors): remove tput

---

misc/scripts/install-local.sh

Postscripts should be as small as possible.
Run `shfmt -mn` on the postscripts.

refactor(postscripts): minify for size

---

misc/scripts/install-local.sh

`dpkg` complains if there is no description.
Add a check.

fix(checks): add check for `description`

---

misc/scripts/install-local.sh
misc/scripts/remove.sh

Because this can happen:
Swap the default ask for replace.

fix(replace): do not prompt for replace

---

misc/scripts/install-local.sh

Because pacstall can freak out otherwise.

fix(checks): add check for name/PACKAGE mismatch

---

misc/scripts/install-local.sh

refactor(func): minify `nproc` lines

---

misc/scripts/install-local.sh

* Added comments explaining more things.
* Unset some loop variables
* Merge 'generate_changelog' echo's into one printf
* Use pushd/popd instead of subshell
* Accurately log Architecture
* Run apt replace check but skip if pacstall package of same name exists
* Remove wget forking for patch[@]

fix(*): assorted fixes

---

pacstall

refactor(pacstall): cut first char in var instead of sed

---

pacstall

It removes a dependency, and won't rely on pipes.

refactor(pacstall): remove `dirname`, use redirection for sed, merge `[[ ]]`

---

install.sh
misc/completion/bash
misc/completion/fish
misc/scripts/add-repo.sh
misc/scripts/search.sh
pacstall

It looks really really bad lol.

feat(pacstallrepo): remove `txt` suffix

---

misc/scripts/install-local.sh

Because `-BI` on a deb package doesn't make much sense, so lets download the deb and exit after that if it's a deb package.

feat(-B): download deb if is deb package

---

misc/scripts/install-local.sh
pacstall

fix(-L,install): missed elif, do not remove dependant

---

pacstall

Because it's only used on one case.

fix(check_url): use fullname instead of appending `/packagelist`

---

misc/scripts/install-local.sh

fix(deb): run preinst if pacstall has it

---

misc/scripts/install-local.sh
misc/scripts/upgrade.sh

Someone doesn't know how to use proper punctuation.
Add `?` to places where we are asking a question, because thats how question marks work.
Done.

fix(pacstall): ask punctuation

---

misc/scripts/dep-tree.sh

It messes with slower terminals and shows visual artifacts.

refactor(dep-tree): remove responsive output

---

misc/scripts/install-local.sh

fix(install): makedepends are too fragile to just remove

---

misc/scripts/install-local.sh

fix(makedeb): log `Build-Depends`

---

misc/scripts/checks.sh
misc/scripts/dep-tree.sh
misc/scripts/install-local.sh
misc/scripts/query-info.sh
misc/scripts/search.sh
pacstall

To prevent packages from being installed/showing up in search.

feat(pacscript): add `mask` array

---

pacstall

upd(pacstall): `4.0.1` -> `4.1.0`

---

misc/scripts/update.sh

It used to say that
Dont do that

fix(update.sh): don't claim master is develop

---

misc/scripts/install-local.sh

Fulfilling the promise of #729.

feat(createdeb): swap `xz` with `zstd`

---

install.sh

fix(install.sh): add `zstd`

---

misc/scripts/install-local.sh

We can add it and it only enhances the quality of the deb.
Add it.

feat(makedeb): add `Vcs-Git` deblog for git packages

---

misc/scripts/install-local.sh

Submodules were never cloned with their parents. 
Pass the flag.

fix(install-local): actually clone submodules

---

misc/scripts/update.sh
pacstall

im too tired to fill this out
you get it

fix(update.sh,pacstall): cleanup -x and update output

---

pacstall

fix(is_apt_package_installed): it works now

---

misc/scripts/checks.sh

fix(checks): `comp_err` variable in `incompatible` check

---

misc/scripts/checks.sh
misc/scripts/install-local.sh
pacstall

It allows more control for package maintainers.
~~@oklopfer wants this because it would prevent many cases of unicorn deleting itself.~~
It can be used for who knows what but it's gonna be added so yeah.

feat: add `priority` key

---

misc/scripts/search.sh

Fix upgrade on multirepo
Append to `$REPOS` instead of overwritting

fix(search.sh): `REPOS` mapfile append

---

misc/scripts/install-local.sh

PKGBUILDs can fetch relative files to them relating to the package like so:
We have some packages like [firefox-developer-edition-bin](https://github.com/pacstall/pacstall-programs/tree/master/packages/firefox-developer-edition-bin) that could benefit from this
incredibly simple change, if `url` doesn't contain `://`, then set `url` = `$pacstallrepo/packages/$pkgname/$url` and attempt to download it like the rest. 
example script below works
```bash
pkgname="firefox-developer-edition-bin"
maintainer="Oren Klopfer <oren@taumoda.com>"
gives="firefox-developer-edition"
pkgver="122.0b9"
pkgdesc="The browser made for developers. All the latest developer tools in beta, plus experimental features like the Multi-line Console Editor and WebSocket Inspector."
source=( …
```

feat(install-local.sh): fetch relative package files

---

install.sh

feat(install.sh): make intro box pretty

---

misc/scripts/build-local.sh
misc/scripts/download-local.sh

feat(download-local): add `nosubmodules` array option

---

misc/scripts/build-local.sh

checks are mixing up things that aren't unsetting oops
unset them

fix(build-local.sh): cleanup `cleanup` unset

---

pacstall

Show on the version if you are in a develop branch (and also fixes version coloring).
Add a check for `/usr/share/pacstall/repo/update`
It's done and tested.

feat(main):  Show if you are in a develop branch when using `-V`

---

misc/scripts/upgrade.sh

fix(upgrade.sh): append `-pacstall1` when missing

---

install.sh
misc/scripts/quality-assurance.sh
misc/scripts/update.sh
pacstall

no need for it to be in nushell tbh
internalize it; used with one of the following:
```bash
pacstall -Qa linux-kernel#5921
pacstall -Qa linux-kernel#5921@github:pacstall/pacstall-programs
pacstall -Qa linux-kernel@github:pacstall/pacstall-programs#5921
```

feat(quality-assurance.sh): internalize `pacstall-qa`

---

misc/scripts/install-local.sh
pacstall

we have verbose and quiet options for everyone now
default to the verbose option, and make it false if -q is provided
also fixing deb download location

feat(main): `-Q/--quiet`

---

misc/scripts/build-local.sh

it wasn't working right before 
update the dirs

fix(build-local.sh): update `KEEP` for 5.0.0 dirs

---

misc/scripts/install-local.sh
pacstall

fix(main,install-local.sh): fix `PACSTALL_VERBOSE` test

---

pacstall

upd(pacstall): `4.3.2` -> `5.0.0`

---

misc/scripts/build.sh
misc/scripts/bwrap.sh
misc/scripts/checks.sh
misc/scripts/fetch-sources.sh
misc/scripts/package.sh
misc/scripts/quality-assurance.sh
misc/scripts/search.sh
misc/scripts/update.sh
misc/scripts/upgrade.sh
pacstall

fix(*): re-run `shfmt` on everything, fix `chmod` perms

---

misc/scripts/quality-assurance.sh

Add the `--keep` and `--build` flags to `-Qa`
Done and tested

fix(quality-assurance): option flags

---

misc/scripts/package.sh

dest was not being provided to the download
provide it

fix(package.sh): repair deb `-B` downloads

---

.github/workflows/workflow.sh
install.sh
misc/scripts/bwrap.sh
misc/scripts/fetch-sources.sh
misc/scripts/quality-assurance.sh
misc/scripts/update.sh
pacstall
uninstall.sh

What the title says
Ctrl+f and replace when needed
I think that's all

ref(*):  Replace directories with the corresponding *DIR variables

---

misc/scripts/fetch-sources.sh
misc/scripts/package.sh

pacup was not exiting on debs
GitHub Actions should return a positive exit on incomps
exit 0

fix(fetch-sources,package): provide needed `exit 0`s

---

misc/scripts/checks.sh

stupid arrays were doubling up
this makes me so sad

fix(checks.sh): fix debs with `source_DISTRO`

---

misc/scripts/build.sh
misc/scripts/srcinfo.sh

forgor to add all alt in one place and srcinfo had a bug with pacdeps
fixem

fix({build,srcinfo}.sh): missed stuff

---

misc/scripts/checks.sh

oieheoriuheo;erhe;osshw;brwoberobhebhioberih;berihoebrhi;ervbohievrih
added in https://github.com/pacstall/pacstall/pull/1131
accidentally removed in https://github.com/pacstall/pacstall/pull/1134
add it. again.

fix(checks.sh): re-add accidentally dropped fix

---

misc/scripts/fetch-sources.sh
misc/scripts/upgrade.sh

sometimes group doesn't exist
drop it, we don't need it
should fix weirdness displayed in https://github.com/pacstall/pacstall-programs/pull/6087 + rhino live images

fix({fetch-sources,upgrade}.sh): don't `chown` with a group

---

misc/scripts/fetch-sources.sh

final &&'s result in return codes for functions
switch to an if check

fix(fetch-sources.sh): fix stacktrace

---

misc/scripts/build.sh

cleanup
ya
https://github.com/pacstall/pacstall-programs/pull/6178 should not be failing

fix(build.sh): only aptitude search when :arch in name

---

misc/scripts/quality-assurance.sh
pacstall

I dont even care anymore
its battle tested
the brave pr thats open rn

fix(pacstall,quality-assurance.sh): repair echo pipes

---

misc/scripts/build.sh
misc/scripts/package.sh
misc/scripts/version-constraints.sh
pacstall

brain gone
exhausted
https://github.com/pacstall/pacstall-programs/pull/6155

fix({build,version-constraints}.sh): exhaust dep searches before failing

---

install.sh
misc/scripts/update.sh
uninstall.sh

files more readable and consistent with each other
we forgor

refactor({install,uninstall,update}.sh): clean up with sanity

---

misc/scripts/build.sh
misc/scripts/package-base.sh
misc/scripts/remove.sh
pacstall

continuation and rebase of #1154

fix(*): cleanup pins and dep files

---

misc/scripts/update.sh

fix(update.sh): drop stacktrace

---

install.sh
misc/scripts/update.sh

fix({install,update}.sh): provide remote spdx-licenses for debian

---

pacstall

fix(stacktrace): use correct variable in check

---

misc/scripts/build.sh
misc/scripts/fetch-sources.sh
misc/scripts/package-base.sh
misc/scripts/package.sh
misc/scripts/search.sh
pacstall
uninstall.sh

pacstall was falling apart
- fix issues with cleanup
- don't accidentally create pacdeps file
- log already installed optdeps as deps
- replace all `/tmp/pacstall-` prefixes with `${PACDIR}-`

fix(*): cleanup stuff

---

misc/scripts/fetch-sources.sh
misc/scripts/package.sh

this is also a valid extension
add it
https://github.com/pacstall/pacstall-programs/pull/6197

fix({fetch-sources,package}.sh): decompress `.tar.bz`/`.tbz` without the `2`

---

misc/scripts/package.sh

deps were made pretty prompted
do it for pacdeps too

feat(package.sh): make pacdeps check prompt pretty

---

misc/scripts/build.sh

we dont want to make the dir unless explicitly keeping
put it in an if check

fix(build.sh): only make `/tmp/pacstall-no-build` with `-K`

---

misc/pacstall.8
pacstall

upd(pacstall): `5.2.1` -> `5.3.0`

---

misc/scripts/package-base.sh
misc/scripts/srcinfo.sh
pacstall

I forgor 2 important ones
add them
also make srcinfo gen work correctly like the one in progs repo
https://github.com/pacstall/pacstall-programs/pull/6205

fix({srcinfo,package-base}.sh): add missing overrides and append arrays

---

misc/pacstall.8
pacstall

upd(pacstall): `5.3.0` -> `5.3.1`

---

misc/scripts/package.sh

it was stacktracing
fix braindead code with a mapfile

fix(package.sh): fix mapping payload_arr

---

misc/scripts/build.sh
misc/scripts/fetch-sources.sh
pacstall

to keep me from freaking out and thinking something is broken
print build + check dep status

fix(fetch-sources.sh): print builddeps like others

---

misc/pacstall.8
pacstall

upd(pacstall): `5.3.1` -> `5.3.2`

---

misc/scripts/fetch-sources.sh

idiot
idiot
https://github.com/pacstall/pacstall-programs/pull/6196

fix(fetch-sources.sh): fix typo in makedep check

---

misc/pacstall.8
pacstall

upd(pacstall): `5.3.2` -> `5.3.3`

---

misc/scripts/srcinfo.sh

https://github.com/pacstall/pacstall-programs/pull/6239
luckily we dont parse this line from internal generation yet, only external, so this isn't urgent

fix(srcinfo.sh): CARCH/AARCH replaces

---

misc/scripts/srcinfo.sh

they are not valid namerefs
substitute . for _
Closes https://github.com/pacstall/pacstall/issues/1191

fix(srcinfo.sh): parse `.` properly

---

misc/scripts/checks.sh
misc/scripts/fetch-sources.sh

if no quote then strings split on their spaces
add quote
Closes #1196

fix({checks,fetch-sources}.sh): quote for loop entries

---

misc/scripts/build.sh

two important vars were not localized
localize them
Closes #1197

fix(build.sh): dependency bleed

---

README.md
misc/scripts/update.sh

ref(update.sh,README.md): remove matrix link

---

misc/man/pacstall.5
misc/man/pacstall.8
pacstall

upd(pacstall): `5.3.3` -> `5.4.0`

---

misc/scripts/manage-repo.sh

these should have been set to false

fix(manage-repo.sh): wrong stack usage

---

install.sh

fix(install.sh): mandir creation

---

misc/man/pacstall.5
misc/man/pacstall.8
pacstall

upd(pacstall): `5.4.0` -> `5.4.1`

---

install.sh
misc/scripts/update.sh

fix({install,update}.sh): linguas newline not space sep

---

.pre-commit-config.yaml

fix(.pre-commit-config.yaml): ignore .po files in codespell

---

misc/scripts/add-repo.sh
misc/scripts/package-base.sh
misc/scripts/package.sh
misc/scripts/search.sh
misc/scripts/upgrade.sh
pacstall

Now we can do stuff like:
```bash
ask "Here is a %s" "string" Y
```

fix(ask): allow for printf usage

---

misc/po/pacstall.pot
misc/scripts/get-pacscript.sh
misc/scripts/package.sh
misc/scripts/update.sh
pacstall

ref(*): use printf syntax for `suggested_solution`

---

pacstall

Elsie didn't test before pushing.
Fix her mistakes.

fix(pacstall): ask + fancy_message interpolation

---

.github/CODEOWNERS

wizard is dead, not sure why he's still even on here
add me so that im auto-marked for review

fix(CODEOWNERS): add `oklopfer`

---

install.sh
pacstall

fix(apt): use proper apt config locations

---

install.sh
pacstall

@Elsie19, go read the documentation about `apt.conf`
Fix Elsie's fuckup.
Use the correct `Dir` in the config
Fixes regression in #1230

fix(install,main): `Cache` -> `State`

---

CODE_OF_CONDUCT.md

Remove DT's politically inclined libertarian CoC. 
Use the Contributors Covenant
Just merge it, we can edit it later, Elsie.
We've been delaying this enough, I'll merge without review because we all agreed to it on the Discord server.

chore: replace DTs CoC with Contributors Covenant

---

pacstall

fix(pacstall): bad cleanup glob

---

misc/scripts/build.sh

vig tricked me into thinking not using the else wouldn't be a problem, but it was
go back to my logic
https://github.com/pacstall/pacstall-programs/pull/6342

fix(build.sh): repair dep else check

---

misc/scripts/fetch-sources.sh

ffmpeg is crazy
```
❯ git ls-remote --tags .
c1738cdff0d3b6426f3e6fd9bf25af7d145ad26f	refs/tags/n4.4.4
71fb6132637a2a430375c24afc381fff8b854fe7	refs/tags/n4.4.4^{}
```
work around this

fix(fetch-sources.sh): annotated commit hashes

---

misc/po/pacstall.pot
misc/scripts/package.sh

fix(package.sh): unremovable, not uninstallable

---

misc/scripts/version-constraints.sh

see https://github.com/pacstall/pacstall/issues/1243
loop over them, as long as at least one of the results satisfies our check, we don't care, apt can take it from there
https://github.com/pacstall/pacstall/issues/1243

fix(version-constraints.sh): loop over multiple provides

---

misc/scripts/build.sh
misc/scripts/fetch-sources.sh

Dep bleeding, seen below, first noticed in #1254
- reverse the return code logic
- make sure everyone prints on their own colors
Closes #1254

fix({build,fetch-sources}.sh): optdeps regression

---

misc/man/pacstall.5
misc/man/pacstall.8
pacstall

upd(pacstall): `5.4.1` -> `5.5.0`

---

misc/po/fr.po

i18n(fr.po): fix backslash

---

misc/po/pacstall.pot
pacstall

breaking out the .deb from the curl install
dont allow update if pacstall is installed from the deb

ref(pacstall)!: do not allow update if dpkg installed

---

misc/po/pacstall.pot
misc/scripts/package.sh

Fixes #1282.
Instead of telling the user it's already installed, show a warning.
@oklopfer idk if pacname and pkgver still refer to what they should so I probably might have messed those up.

feat(package): show reinstall warning

---

misc/scripts/bwrap.sh
misc/scripts/fetch-sources.sh
misc/scripts/package.sh
pacstall

forgor to do this part almost
its been replaced by extract-to syntax

ref(*)!: remove `_archive` internal var

---

misc/man/pacstall.5
misc/man/pacstall.8
misc/po/pacstall.pot
pacstall

I still have to update the wiki and add the how to blurb in the release notes

upd(pacstall): `5.5.0` -> `6.0.0`

---

misc/scripts/version-constraints.sh

Big yikes.
1. Set `ret=1` by default.
2. Fix broken handling of installed packages.

fix(version-constraints): fix missing version checks for installed packages

---

misc/scripts/build.sh

fix(build.sh): make all maintainers uploaders

---

misc/po/pacstall.pot
misc/scripts/fetch-sources.sh

It looks weird the way it was, and it makes translating way more easy.

fix(fetch-sources): use more natural language

---

misc/man/pacstall.5
misc/man/pacstall.8
pacstall

upd(pacstall): `6.0.0` -> `6.0.1`

---

misc/scripts/build.sh

fix(build.sh): emergency fix

---

misc/man/pacstall.5
misc/man/pacstall.8
pacstall

upd(pacstall): `6.0.1` -> `6.0.2`

---

misc/scripts/bwrap.sh

need it for pkgbase packages like nerd fonts

fix(bwrap.sh): share `pacname` + `pkgbase`

---

misc/scripts/package.sh
misc/scripts/quality-assurance.sh
pacstall

feat(pacstall): add special debug flag

---

misc/scripts/package.sh

fix(package.sh): no warn on build

---

misc/man/pacstall.5
misc/man/pacstall.8
pacstall

upd(pacstall): `6.0.2` -> `6.1.0`

---

misc/po/ta.po

- Added translation for Tamil as ta.po file
- Which is a extra feature to add Language Tamil (India) specifically for pacstall
-  [X] copy ta.po from pacstall.pot
-  [X] installed 'gettext po syntax highlighter extension' from my vscode for better syntax highlighting to reduce mistakes while translation
-  [X] translate from english in msgid to tamil in msgstr
I feel , I havent added 2 or 3 translations, which feels more confusing to translate. I almost covered more than 90% of my translations from english to tamil

feat: added tamil translation .po file

---

misc/scripts/srcinfo.sh

fix(srcinfo.sh): fix logging gives_CARCH

---

misc/scripts/build.sh

pipes that were also constrained were read wrong
fix it by decompiling to what pacstall normally expects for its dep arrays
https://github.com/pacstall/pacstall-programs/actions/runs/13023823488/job/36329479103?pr=6965

fix(build.sh): fix repacstall dep array making

---

misc/man/pacstall.5
misc/man/pacstall.8
pacstall

upd(pacstall): `6.1.0` -> `6.1.1`

---

misc/scripts/upgrade.sh
pacstall

AJ wants it for something idk
Create a command that forks normal `-Up` and disables final prompting

feat(upgrade.sh): add list only option

---

misc/man/pacstall.5
misc/man/pacstall.8
pacstall

upd(pacstall): `6.1.1` -> `6.2.0`

---

misc/scripts/package.sh
misc/scripts/query-info.sh

See https://github.com/rhino-linux/rhino-pkg/pull/52#issuecomment-2707342730 for full context.

fix({package,query-info}.sh): provide pacstall ver

---

misc/man/pacstall.5
misc/man/pacstall.8
pacstall

upd(pacstall): `6.3.0` -> `6.3.1`

---

misc/scripts/build.sh

google earth thing we were just talking about
chmod fix no recursive
https://github.com/pacstall/pacstall-programs/pull/7556

fix(build.sh): own repacstall dir

---

misc/man/pacstall.5
misc/man/pacstall.8
pacstall

upd(pacstall): `6.3.1` -> `6.3.2`

---

install.sh
misc/scripts/update.sh

why did they do this? are they stupid?
switch to wget
https://github.com/rhino-linux/tracker/issues/80

fix({update,install}.sh): use wget

---

install.sh
misc/scripts/update.sh

fix({install,update}.sh): ensure curl and wget always
